////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[NetSteps]]
:imagesdir: ../../assets/images
:page-pagination:
:page-pagination-no-next:
:description: Getting Started (8/8): You now know the basic Hop terminology and tools, and you've created and have run your first pipeline and workflow. Here's an overview of topics you could explore to continue building your Hop knowledge.

= Next Steps

You now know what Hop is and how to create your first workflows and pipelines.

There's a lot more to discover in Hop.
Here are a couple of topics you may want to look into:

* xref:pipeline/pipelines.adoc[Pipelines] takes closer look at the various aspects of creating and running pipelines, and contains the entire list of transforms that are at your disposal
* xref:workflow/workflows.adoc[Workflows] takes a closer look at the various aspects of create and running workflows, and contains the entire list of actions that are at your disposal
* xref:best-practices/index.adoc[Best Practices] covers a number of things you might want to think about while using Apache Hop.
* xref:projects/index.adoc[Projects] explains how to work with projects and environments
* xref:vfs.adoc[VFS] explains how you can access resources in the 3 main cloud platforms: AWS, Azure and GCP.
* xref:logging/logging-basics.adoc[Logging] explains how to configure Hop for your desired log level and target platform
