////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[DownloadInstall]]
:imagesdir: ../../assets/images
:page-pagination:
:description: Getting Started (3/8): Installing Hop is as easy and accessible as possible: download, unzip, start.

= Download and Install Hop

Hop is designed to be as easy and accessible to use as possible.

Getting and starting Hop couldn't be easier:

== Download

Download Hop from the http://hop.apache.org/download/[downloads page].

== Prerequisites

Hop is self contained, all you need is a Java runtime.
Hop has been developed and tested with Java 8, but you shouldn't have any issues running Hop with Java 11. Check the https://java.com/en/download/help/download_options.html[Java docs] to download and install a Java runtime for your operating system.

== Install

Unzip Hop to a folder of your choice.
From that folder, you'll be able to run the different Hop xref:hop-tools/index.adoc[tools] through their corresponding scripts.

Now that you have Hop installed, let's have a look at all of the Hop tools you have at your disposal.


