////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[HopConcepts]]
:imagesdir: ../../assets/images
:page-pagination:
:description: Getting Started (2/8): before going into the details of workflows and pipelines, we'll walk through the core terminology used in Hop.

= Hop Concepts

== Core Concepts

Before we dive deeper, let's take a minute to familiarize ourselves with the Hop lingo.

**Metadata** is by far the most important concept in all of Hop.
Every item we'll cover below is defined as metadata.
All interactions between Hop and other components in your data architecture are done through metadata.
_Metadata is at the core of **everything** in Hop_.


* **Pipelines** are collections of **transforms**, connected by **hops**.
All transforms in a pipeline run in parallel.

* **Workflows** are collections of **actions**, connected by **hops**.
All actions in a workflow run sequentially by default.

* **Projects** are logical collections of hop code and configuration.
**Environments** contain the environment-specific (e.g. dev, uat, prd) metadata.

include::../snippets/hop-concepts/item-types.adoc[]

include::../snippets/hop-concepts/hop-projects-environments.adoc[]
