////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[GettingStarted]]
:imagesdir: ../../assets/images
:page-pagination:
:page-pagination-no-back:
:description: The Apache Hop Getting Started guide walks new Hop users through the Hop concepts and the bare necessities to get started building workflows and pipelines.

= Getting Started

This guide walks you through the Hop basics.

We'll focus on the core knowledge you need to move around in Hop, without going in detail.
At the end of this guide, there will be links to dive deeper into various Hop topics.

This is what we'll cover:

* xref:getting-started/hop-what-is-hop.adoc[What is Hop?]
* xref:getting-started/hop-concepts.adoc[Concepts]
* xref:getting-started/hop-download-install.adoc[Download & Install]
* xref:getting-started/hop-tools.adoc[Tools]
* xref:getting-started/hop-gui.adoc[Hop Gui overview]
* xref:getting-started/hop-gui-pipelines.adoc[Pipelines]
* xref:getting-started/hop-gui-workflows.adoc[Workflows]
* xref:getting-started/hop-next-steps.adoc[Next Steps]

