////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[HopGui]]

:description: Hop Gui is Hop's visual development environment where you will mainly design, run and debug workflows and pipelines, but Hop Gui has a lot more to offer: you can configure all of your metadata items like database connections, run configurations etc. You can search, manage files, version control your work and more.


= Hop Gui

Hop Gui is Hop's visual development environment. You'll spend a lot of time here in the various perspectives of Hop GUI.

You'll spend most of your time building, previewing running and debugging workflows and pipelines, but there's also a lot of configuration that can be done from Hop Gui's metadata perspective, you can search for any metadata with the search perspective, manage a variety of files and even version control them from the file explorer perspective and much more.

This page covers a number of topics that are very specific to working with Hop Gui.
Check the chapters on xref:/pipeline/pipelines.adoc[pipelines] and xref:/workflow/workflows.adoc[workflows] to learn more about creating and running pipelines and workflows in Hop Gui.

Covered here are:

* xref:hop-gui/file-dialog.adoc[File Dialog]: the versatile Hop file browser and chooser dialog.
* xref:hop-gui/hop-gui-popup-dialog.adoc[Popup Dialog]: the versatile popup dialog to work with metadata, workflows, pipelines and hops
* xref:hop-gui/perspectives.adoc[Perspectives]: the various perspectives in the Hop Gui
* xref:hop-gui/hop-gui-git.adoc[Working with git]: Manage files in the git version control system
* xref:hop-gui/shortcuts.adoc[Keyboard Shortcuts]: a list of the keyboard shortcuts that are available in Hop Gui.
* xref:hop-gui/hop-web.adoc[Hop Web]: a web version of Hop Gui that provides the exact same functionality and user experience as the desktop version
