////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../assets/images

== Neo4j Perspective

Icon: image:icons/neo4j_logo.svg[width="24px"]

Description::
The Neo4j perspective provides a view on and allows you to query Hop execution history from a Neo4j database.

The perspective shows the value the `NEO4J_LOGGING_CONNECTION` (used to load execution logging to Neo4j), allows to select a workflow or pipeline to display logging for (optionally, specify the number of executions and only show root executions).

For the selected workflow or pipeline, or all executions if none selected), the id, name, type, number of rows read, written, input, output and rejected, the number of error rows and the execution date and duration are shown.

In the bottom half of the perspective dialog, the logging text, path to errors and a number of useful cypher queries are shown.