////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[Shortcuts]]
:imagesdir: ../assets/images
:description: A lot of actions in Hop can be performed significantly faster through keyboard shortcuts.

= Hop Shortcuts

Most shortcuts can be found inside the application itself. In the Settings perspective there is a tab named Keyboard Shortcuts that lists global chords and where to use them.

Widget-local shortcuts (they apply to the focused field, not the whole window) are not listed there:

[options="header"]
|===
|Shortcut|Where|What it does
|`CTRL-SPACE`|`TextVar` / `ComboVar` that accept variables|Insert a `${variable}`
|`CTRL-SPACE`|Name fields that do *not* accept variables (transform/action/metadata names)|Apply a xref:metadata-types/naming-scheme.adoc[Naming Scheme] of the matching type
|`CTRL-SHIFT-N`|Any name field, field-name cell, table name, file/folder field, or F2 tree rename|List and apply a Naming Scheme. Replaces the current identifier (values that contain `${...}` are left unchanged)
|===

See xref:metadata-types/naming-scheme.adoc[Naming Scheme] for the *N* indicator, types, and the TableView bulk toolbar.
