////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[password-plugins]]
= Passwords and Password Plugins

Hop provides password obfuscation as a way to prevent storing passwords as clear text.

Obfuscation is the deliberate act of creating source or machine code that is difficult for humans to understand[https://en.wikipedia.org/wiki/Obfuscation_(software)[1]].

With obfuscated passwords, Hop provides a way to store passwords in a way the makes them hard (but not impossible!) to read.
Obfuscated passwords are read by Hop and are converted to the original password as late as possible (e.g. to pass to a database when creating a connection).

== Password obfuscation in Hop

Obfuscate passwords are stored in Hop metadata with the 'Encrypted' prefix. The example below shows a database connection with an obfuscated password 'abcd.

[source,json]
----
{
  "rdbms": {
    "POSTGRESQL": {
      "databaseName": "DBNAME",
      "pluginId": "POSTGRESQL",
      "indexTablespace": "",
      "dataTablespace": "",
      "accessType": 0,
      "hostname": "localhost",
      "password": "Encrypted 2be98afc86aa7f2e4cb79ce10df90acde",
      "port": "5432",
      "pluginName": "PostgreSQL",
      "servername": "",
      "attributes": {},
      "username": "dbuser"
    }
  },
  "name": "DBCONN"
}
----

== Password obfuscation in Hop Server

Obfuscated passwords for Hop Server can be stored in the server's .pwd file.

In the example below, Hop's default server hop.pwd contains the username 'cluster' and the default obfuscated passowrd 'cluster'
, with the 'OBF:' prefix.

[source,bash]
cluster: OBF:1v8w1uh21z7k1ym71z7i1ugo1v9q,default

== Password Encryption (Obfuscation) with Hop Encrypt

Check xref:hop-tools/hop-encrypt.adoc[Hop Encrypt] for more information on how to obfuscate or encrypt password for use in Hop or Hop Server.

== Password plugins

Password handling  in Hop can be implemented as plugins.

The following plugin implementations are available:

* xref:password/passwords/aespasswords.adoc[AES Two Way Password Encoder]