////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/terafast/src/main/doc/terafast.adoc

= Teradata Bulk Loader

== Description

The Teradata Bulkloader transform supports fastloading data into a Teradata database using the fastload command line tool.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Use control file| Work in control file mode. 
|Control file|The path to the control file to be used.
|Variable Substitution in control file|Make use of POI Variables (eg: ${RUN_ID}) in the control file.
|Path to fastload|The path to the fastload command line utility.
|Error log|An optional Error log to be created by Fastload.
|Connection|A connection to the Teradata DB.
|Target table|The table to be loaded.
|Truncate table|Truncate the target table before loading.
|Data file|The name of the temporary data file.
|Sessions|Number of sessions to be used by Fastload.
|Error limit|The error limit for Fastload.
|Field mapping|Definition of POI <-> DB Field mapping.
|===

=== Fastload Control File

Runs as a transform within a pipeline completely independent from other transforms.