////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/deletefolders/src/main/doc/deletefolders.adoc
= Delete Folders

== Description

This workflow action deletes a set of folders and their content.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Settings|Copy previous results to args: Enable this option if the folders you want to delete come from the result files of the previous action in the workflow.
|Success on a|Success condition : select one of :
* When no error reported : everything deleted just fine
* When at least x folders processed : specify x in the Limit field below
* When the number of errors less than : specify the max nr of errors in the limit field below
|Folders a|This is the list of all the folders to delete.  You can use the Folder field and these buttons to maintain the list:

* Add : add Folder field to the list of folders
* Folder ... : select a folder
* Delete : remove the selected folders from the list
* Edit : move the selected folder to the Folder field for editing
|===