////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/clonerow/src/main/doc/clonerow.adoc
= Clone row

== Description

This transform creates copies (clones) of a row and outputs them directly after the original row to the next transforms.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform. Note: This name has to be unique in a single pipeline.
|Nr clones|The number of clones you want to add after the original row.
|Add clone flag a|Check this option if you want to add a boolean field in the output indicating if the row is a clone or not.

* N / false : this is not a cloned row, it's the original row
* Y / true : this is a cloned row, a copy of the original row
|Clone flag field|The name of the clone flag field 
|===