////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/filesexist/src/main/doc/filesexist.adoc
= Checks if files exists

== Description

Use the Checks if files exists action to verify that specified files exist.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action. This name has to be unique in a single workflow.
|File/folder name|The file or folder.
|Add|Adds the file or folder to the Files/Folders table.
|File...|Browse the filesystem for a file.
|Folder...|Browse the filesystem for a folder.
|Files/Folders|The table containing the files or folders to check.
|Delete|Deletes the selected file or folder from the table.
|Edit|Moves the file or folder from the table to the File/folder to the File/folder name edit field.
|===

