////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Apache Hop logging architecture and concepts.

[[LoggingArchitecture-LoggingArchitecture]]
= Logging

== Introduction
Apache Hop's logging architecture is mostly readable from our source code.
In the following sections, we provide a general layout and concepts to get familiar with.

== HopLogStore
The `HopLogStore.getInstance()` is where Channels are able to store and append their logs.
HopLogStore is initialized when you run `HopEnvironment.init()`

== Channels
Every runtime object (IPipelineEngine, IWorkflowEngine, etc.) in Apache Hop has a log channel ID with which you can examine the HopLogStore for what was logged for an ID.

== Logging Registry
The logging hierarchy is in `LoggingRegistry.getInstance()`

== Log text
To get logging text you can do something like: `HopLogStore.getInstance().getAppender().getBuffer(pipeline.getLogChannelId(), true);`