////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Apache Hop logging from UDJC.

[[UDJCLogging-UDJCLogging]]
= UDJC Logging

== Introduction
UDJC (User Defined Java Classes) allow for logging statements such as `logBasic("test");`.

The logs are stored in the following manner:

- It goes to a Hop logging channel.
- It ends up in `HopLogStore.getInstance()` which is initialized when you run `HopEnvironment.init()`
- The logging hierarchy is in `LoggingRegistry.getInstance()`
- The logging text can be accessed with something like: `HopLogStore.getInstance().getAppender().getBuffer(pipeline.getLogChannelId(), true);`
