////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/flattener/src/main/doc/flattener.adoc
= Row Flattener

== Description

The Row Flattener transform allows you flatten data sequentially.

== Options

[width="90%", options="header"]
|===
|Option|Description
|transform name|Name of the transform; this name has to be unique in a single pipeline
|The field to flatten|The field that must be flattened into different target fields
|Target fields|The name of the target field to which the field is flattened
|===

== Example

In the sample below, if you begin with the following data set...
[width="90%", options="header"]
|===
|Field1|Field2|Field3|Flatten
|A|B|C|One
|Z|Y|X|Two
|D|E|F|Three
|W|V|U|Four
|===

The data set can be flattened to the example shown below:
[width="90%", options="header"]
|===
|Field1|Field2|Field3|Target1|Target2
|A|B|C|One|Two
|D|E|F|Three|Four
|===
