////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[HopRest]]
:imagesdir: ../assets/images
:description: hop-rest is a web application (and docker container) which is capable of working with the Hop ecosystem.

:toc:

= Hop REST Web Application

== Description

The Hop REST web application is deployed as a WAR file `hop-rest-<version>.war`.  You can put this archive in the `webapps` folder of your favorite server (e.g. Apache Tomcat).  We suggest that you rename it to `hop.war` or that you unzip it in a `hop` folder.

== The base URL

When deployed under a `webapps/hop` folder you will get the services, detailed below, under the base URL of `/hop/api/v1/`.

== Metadata services

The metadata services are deployed under sub-path `metadata/`.

=== List the metadata type keys

[cols="1,2"]
|===
|Type
|`GET`

|Path
|`metadata/types`

|Produces
|`application/json`

|Example call
|`curl -X GET http://localhost:8080/hop/api/v1/metadata/types`

|Example output
|
`["dataset","workflow-log","async-web-service","execution-info-location","web-service","cassandra-connection","workflow-run-configuration","unit-test","rdbms","mongodb-connection","file-definition","splunk","pipeline-run-configuration","pipeline-log","server","partition","execution-data-profile","neo4j-connection","pipeline-probe","neo4j-graph-model"]`

|===

=== List the metadata elements for a key

[cols="1,2"]
|===
|Type
|`GET`

|Path
|`metadata/list/{key}`

|Arguments
|`key` : the key of the metadata type

|Produces
|`application/json`

|Example call
|`curl -X GET http://localhost:8080/hop/api/v1/metadata/list/pipeline-run-configuration/`

|Example output
|
`["local"]`

|===

=== Get a metadata element

[cols="1,2"]
|===
|Type
|`GET`

|Path
|`metadata/{key}/{name}`

|Arguments
|`key` : the key of the metadata type, `{name}` : the name of the metadata element to get.

|Produces
|`application/json`

|Example call
|`curl -X GET http://localhost:8080/hop/api/v1/metadata/pipeline-run-configuration/local/`

|Example output
|
`{"engineRunConfiguration":{"Local":{"feedback_size":"50000","sample_size":"1000","sample_type_in_gui":"None","wait_time":"2","rowset_size":"10000","safe_mode":false,"show_feedback":false,"topo_sort":false,"gather_metrics":false,"transactional":false}},"defaultSelection":false,"configurationVariables":[],"name":"local","description":"Runs your pipelines locally with the standard local Hop pipeline engine","dataProfile":"first-last","executionInfoLocationName":"local"}`

|===

=== Save a metadata element

[cols="1,2"]
|===
|Type
|`POST`

|Path
|`metadata/{key}`

|Arguments
|`key` : the key of the metadata type to save

|Consumes
|`application/json`

|Produces
|`application/json`

|Example call
|`curl -X POST http://localhost:8080/hop/api/v1/metadata/pipeline-run-configuration/ -d '{"engineRunConfiguration":{"Local":{"feedback_size":"50000","sample_size":"1000","sample_type_in_gui":"None","wait_time":"2","rowset_size":"10000","safe_mode":false,"show_feedback":false,"topo_sort":false,"gather_metrics":false,"transactional":false}},"defaultSelection":false,"configurationVariables":[],"name":"local","description":"Runs your pipelines locally with the standard local Hop pipeline engine","dataProfile":"first-last","executionInfoLocationName":"local"}'`

|===


== Plugins services

The plugins services are deployed under sub-path `plugins/`.

=== List all the plugin type classes

[cols="1,2"]
|===
|Type
|`GET`

|Path
|`plugins/types`

|Produces
|`application/json`

|Example call
|`curl -X GET http://localhost:8080/hop/api/v1/plugins/types`

|Example output
|
`["org.apache.hop.core.compress.CompressionPluginType","org.apache.hop.core.row.value.ValueMetaPluginType","org.apache.hop.core.database.DatabasePluginType","org.apache.hop.core.plugins.TransformPluginType","org.apache.hop.core.auth.AuthenticationConsumerPluginType","org.apache.hop.imp.ImportPluginType","org.apache.hop.core.encryption.TwoWayPasswordEncoderPluginType","org.apache.hop.core.auth.AuthenticationProviderPluginType","org.apache.hop.core.plugins.PartitionerPluginType","org.apache.hop.core.logging.LoggingPluginType","org.apache.hop.execution.plugin.ExecutionInfoLocationPluginType","org.apache.hop.core.config.plugin.ConfigPluginType","org.apache.hop.core.plugins.HopServerPluginType","org.apache.hop.core.plugins.ActionPluginType","org.apache.hop.core.extension.ExtensionPointPluginType","org.apache.hop.pipeline.engine.PipelineEnginePluginType","org.apache.hop.pipeline.transform.RowDistributionPluginType","org.apache.hop.workflow.engine.WorkflowEnginePluginType","org.apache.hop.core.vfs.plugin.VfsPluginType","org.apache.hop.execution.sampler.ExecutionDataSamplerPluginType","org.apache.hop.metadata.plugin.MetadataPluginType"]`

|===

=== List all the plugins for a given type class

[cols="1,2"]
|===
|Type
|`GET`

|Path
|`metadata/list/{typeClassName}/`

|Arguments
|`key` : the class name of the plugin type

|Produces
|`application/json`

|Example call
|`curl -X GET http://localhost:8080/hop/api/v1/plugins/list/org.apache.hop.pipeline.engine.PipelineEnginePluginType`

This call retrieves all the information about all the pipeline engine plugins.

|Example output
|
`[{"category":null,"name":"Beam DataFlow pipeline engine","description":"This allows you to run your pipeline on Google Cloud Platform DataFlow, provided by the Apache Beam community","ids":["BeamDataFlowPipelineEngine"],"pluginType":"org.apache.hop.pipeline.engine.PipelineEnginePluginType","imageFile":null,"separateClassLoaderNeeded":false,"classLoaderGroup":null,"nativePlugin":false, ... }`

|===

== Service services

The 'Service' services are deployed under sub-path `services/`.

=== Execute a pipeline synchronously

[cols="1,2"]
|===
|Type
|`POST`

|Path
|`services/sync`

|Produces
|`application/json`

|Example call
|`curl -X POST  http://localhost:8080/hop/api/v1/service/sync/  -H 'Content-Type: application/json'  -d '{ "service" : "test", "runConfig" : "local", "variables" : { "VAR1" : "value1", "VAR2" : "value2" }, "bodyContent" : "This is body content" }'`
`
|Example output
|The executing pipeline can produce output like this:

`{
"rows" : [ {
"id" : 1,
"uuid" : "93b534f0-31ef-4992-8012-ffbfd3d7d489",
"var1" : "value1",
"var2" : "value2",
"bodyContent" : "This is body content"
}, ... ]
}`

|===

The body to post can contain the following options (see also: the example above)

* `service`: the name of the Web Service metadata element to use
* `runConfig`: the name of the pipeline run configuration to use
* `variables`: a map with variables (or parameters) with their names and values
* `bodyContent`: this will be set as a variable using the body content variable option in the Web Service metadata.

