////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/filelocked/src/main/doc/filelocked.adoc
= Check if file is locked

== Description

This transform tries to determine if a file is locked by an other process.  It does this by trying to move it to itself.  

== Options


* transform name: the transform name, unique in a pipeline
* Filename field: the name of the input field that will contain the names of the files during execution.
* Result fieldname: the name of the Boolean output field that will contain true or false depending on whether or not the file is locked or not.
* Add filename to result: check this if you want to add the checked file-names to the list of files in the pipelines result.
