/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.setup.persist;

import java.util.Map;
import org.apache.commons.lang3.StringUtils;
import org.apache.hop.setup.HopSetupException;
import org.apache.hop.setup.OsFamily;

/** Generates hop-env.sh / hop-env.cmd. Existing process env is left unchanged when sourced. */
public final class EnvScriptWriter {

  private EnvScriptWriter() {}

  public static String render(OsFamily os, Map<String, String> variables) throws HopSetupException {
    return os.isWindows() ? windowsScript(variables) : unixScript(variables);
  }

  public static String unixScript(Map<String, String> variables) throws HopSetupException {
    StringBuilder out = new StringBuilder();
    out.append("# Generated by hop setup. Sourced by Hop launchers when present at the well-known")
        .append(" path.\n");
    out.append("# Existing environment variables are left unchanged.\n");
    for (Map.Entry<String, String> entry : variables.entrySet()) {
      if (StringUtils.isEmpty(entry.getValue())) {
        continue;
      }
      String quoted = EnvValueEscaper.shellSingleQuoted(entry.getKey(), entry.getValue());
      out.append("if [ -z \"${")
          .append(entry.getKey())
          .append("}\" ]; then export ")
          .append(entry.getKey())
          .append('=')
          .append(quoted)
          .append("; fi\n");
    }
    return out.toString();
  }

  public static String windowsScript(Map<String, String> variables) throws HopSetupException {
    StringBuilder out = new StringBuilder();
    out.append("@echo off\r\n");
    out.append("REM Generated by hop setup. Called by Hop launchers when present at the")
        .append(" well-known path.\r\n");
    out.append("REM Existing environment variables are left unchanged.\r\n");
    for (Map.Entry<String, String> entry : variables.entrySet()) {
      if (StringUtils.isEmpty(entry.getValue())) {
        continue;
      }
      out.append("if not defined ")
          .append(entry.getKey())
          .append(' ')
          .append(EnvValueEscaper.cmdAssignment(entry.getKey(), entry.getValue()))
          .append("\r\n");
    }
    return out.toString();
  }
}
