////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/engines/beam/src/main/doc/beambigqueryoutput.adoc
= Beam BigQuery Output

== Description

The Beam BigQuery Input transform can be used to input data from link:https://cloud.google.com/bigquery[BigQuery] using the Beam execution engine.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Project ID|The Google Cloud Platform project.
|Data set ID|The BigQuery dataset ID.
|Table ID|The BigQuery table ID.
|Create table if needed|Whether or not to create the table if it does not exist.
|Truncate table|Whether or not to truncate the table before inserting.
|Fail if the table is not empty|Throws an error if the table is not empty.
|===