////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/engines/beam/src/main/doc/beaminput.adoc
= Beam Input

== Description

The Beam Input transform reads files using a file definition with the Beam execution engine.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Input location|The location from which to read a file.
|File definition to use|The file definition to use stored in a metastore.
|Edit|Edits an existing file definition.
|New|Creates a new file definition.
|Manage|Opens the MetaStore Explorer.
|===

== File Definition

A file definition can be used to define a file structure definition.

[width="90%", options="header"]
|===
|Option|Description
|Name|The file definition name.
|Description|The file definition description.
|Field separator|The character separating the fields.
|Field enclosure|The character enclosing fields.
|Field definitions|A list of fields.
|Field name|The field name.
|Type|The field data type.
|Format|The field format.
|Length|The field length.
|Precision|The field precisiom.
|===