////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/syslog/src/main/doc/syslog.adoc
= Send information using Syslog

== Description

The Send information using Syslog action can be used to send a message using link:https://en.wikipedia.org/wiki/Syslog[syslog].

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Server name / IP address|The server host.
|Server port|The server port.
|Facility|A facility code is used to specify the type of program that is logging the message. 
|Priority|The severity of the message.
|Add hostname to message|
|Add timestamp to message|
|Date pattern|The format of the date.
||The message to send.
|===
