/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.lint;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.apache.hop.lint.registry.YamlRulePackParser;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Writing a decision into the project's lint configuration.
 *
 * <p>The file belongs to the user: it is version controlled, reviewed, and usually commented. These
 * pin the two things that would make the feature not worth having — losing what is already in the
 * file, and writing something that no longer parses.
 */
public class LintPolicyYamlWriterTest {

  @TempDir private Path dir;

  private Path yaml() {
    return dir.resolve("hop-lint.yml");
  }

  private String read() throws IOException {
    return Files.readString(yaml(), StandardCharsets.UTF_8);
  }

  private LintPolicy policy() throws IOException {
    return YamlRulePackParser.parseProjectYaml(yaml().toFile()).getPolicy();
  }

  @Test
  public void createsTheFileWhenThereIsNoneYet() throws Exception {
    LintPolicyYamlWriter.addExclude(yaml(), "templates/**", "Metadata injection templates");

    assertEquals(List.of("templates/**"), policy().getExcludes());
  }

  @Test
  public void addsToTheBlockThatIsAlreadyThere() throws Exception {
    Files.writeString(
        yaml(),
        """
        # Our project rules, reviewed 2026-01-14
        exclude:
          # generated by the importer
          - "generated/**"

        rules:
          TRANS-002:
            enabled: false
        """,
        StandardCharsets.UTF_8);

    LintPolicyYamlWriter.addExclude(yaml(), "templates/**", null);

    assertEquals(List.of("generated/**", "templates/**"), policy().getExcludes());

    String updated = read();
    assertTrue(updated.contains("# Our project rules, reviewed 2026-01-14"), updated);
    assertTrue(updated.contains("# generated by the importer"), updated);
    assertTrue(updated.contains("enabled: false"), updated);
  }

  @Test
  public void suppressionCarriesRulePathSourceAndReason() throws Exception {
    LintPolicyYamlWriter.addSuppression(
        yaml(), "HOP-CHECK", "templates/load.hpl", "Fonte Sql", "Injected at runtime");

    List<LintPolicy.Suppression> suppressions = policy().getSuppressions();
    assertEquals(1, suppressions.size());
    assertEquals("HOP-CHECK", suppressions.get(0).getRuleId());
    assertEquals("templates/load.hpl", suppressions.get(0).getPath());
    assertEquals("Fonte Sql", suppressions.get(0).getSource());
    assertEquals("Injected at runtime", suppressions.get(0).getReason());
  }

  /** A reason with a quote in it must not end the YAML string early. */
  @Test
  public void awkwardTextIsQuoted() throws Exception {
    LintPolicyYamlWriter.addSuppression(
        yaml(), "HOP-CHECK", "*.hpl", null, "The \"template\" pipeline: fields\narrive later");

    LintPolicy.Suppression suppression = policy().getSuppressions().get(0);
    assertEquals("*.hpl", suppression.getPath());
    assertEquals("The \"template\" pipeline: fields arrive later", suppression.getReason());
  }

  @Test
  public void bothBlocksCanGrowIndependently() throws Exception {
    LintPolicyYamlWriter.addExclude(yaml(), "generated/**", null);
    LintPolicyYamlWriter.addSuppression(yaml(), "DB-001", null, null, "Pinned until the migration");
    LintPolicyYamlWriter.addExclude(yaml(), "tests/**", null);

    assertEquals(List.of("generated/**", "tests/**"), policy().getExcludes());
    assertEquals(1, policy().getSuppressions().size());
  }

  @Test
  public void removingASuppressionLeavesTheRestOfTheFileAlone() throws Exception {
    Files.writeString(
        yaml(),
        """
        # Reviewed by the data team
        suppress:
          - rule: HOP-CHECK
            path: "templates/load.hpl"
            source: "Fonte Sql"
            reason: "Injected at runtime"
          - rule: DB-001
            path: "legacy/old.hpl"
            reason: "Pinned until the migration"

        rules:
          TRANS-002:
            enabled: false
        """,
        StandardCharsets.UTF_8);

    int removed =
        LintPolicyYamlWriter.removeSuppressionsFor(yaml(), "templates/load.hpl", "Fonte Sql");

    assertEquals(1, removed);
    List<LintPolicy.Suppression> left = policy().getSuppressions();
    assertEquals(1, left.size());
    assertEquals("DB-001", left.get(0).getRuleId());

    String updated = read();
    assertTrue(updated.contains("# Reviewed by the data team"), updated);
    assertTrue(updated.contains("enabled: false"), updated);
  }

  /** Everything the dialog wrote for one element comes back out, whatever rules it named. */
  @Test
  public void removingTakesOutEveryRuleRecordedForTheElement() throws Exception {
    LintPolicyYamlWriter.addSuppression(yaml(), "HOP-CHECK", "t.hpl", "Fonte Sql", "why");
    LintPolicyYamlWriter.addSuppression(yaml(), "TRANS-002", "t.hpl", "Fonte Sql", "why");
    LintPolicyYamlWriter.addSuppression(yaml(), "HOP-CHECK", "t.hpl", "Salva S3", "why");

    assertEquals(2, LintPolicyYamlWriter.removeSuppressionsFor(yaml(), "t.hpl", "Fonte Sql"));

    List<LintPolicy.Suppression> left = policy().getSuppressions();
    assertEquals(1, left.size());
    assertEquals("Salva S3", left.get(0).getSource());
  }

  /** An empty suppress: key reads as an oversight, so the last entry takes it with it. */
  @Test
  public void removingTheLastEntryDropsTheBlock() throws Exception {
    LintPolicyYamlWriter.addSuppression(yaml(), "HOP-CHECK", "t.hpl", "Fonte Sql", "why");

    LintPolicyYamlWriter.removeSuppressionsFor(yaml(), "t.hpl", "Fonte Sql");

    assertEquals(List.of(), policy().getSuppressions());
    assertTrue(!read().contains("suppress:"), read());
  }

  @Test
  public void removingWhatIsNotThereChangesNothing() throws Exception {
    LintPolicyYamlWriter.addExclude(yaml(), "generated/**", null);
    String before = read();

    assertEquals(0, LintPolicyYamlWriter.removeSuppressionsFor(yaml(), "t.hpl", "Fonte Sql"));
    assertEquals(before, read());
  }

  /** Excluding is a menu click, so putting the file back has to be one too. */
  @Test
  public void anExclusionCanBeTakenBackOut() throws Exception {
    Files.writeString(
        yaml(),
        """
        # Keep the importer output out of it
        exclude:
          - "generated/**"
          # dynamic from end to end
          - "templates/load.hpl"

        rules:
          TRANS-002:
            enabled: false
        """,
        StandardCharsets.UTF_8);

    assertTrue(LintPolicyYamlWriter.removeExclude(yaml(), "templates/load.hpl"));

    assertEquals(List.of("generated/**"), policy().getExcludes());
    String updated = read();
    assertTrue(updated.contains("# Keep the importer output out of it"), updated);
    assertTrue(updated.contains("enabled: false"), updated);
    // The comment written above the entry described it, and goes with it.
    assertTrue(!updated.contains("dynamic from end to end"), updated);
  }

  @Test
  public void removingTheLastExclusionDropsTheBlock() throws Exception {
    LintPolicyYamlWriter.addExclude(yaml(), "templates/load.hpl", "dynamic");

    assertTrue(LintPolicyYamlWriter.removeExclude(yaml(), "templates/load.hpl"));

    assertEquals(List.of(), policy().getExcludes());
    assertTrue(!read().contains("exclude:"), read());
  }

  /** A file covered by a broader pattern is left to the user: which entry to change is a choice. */
  @Test
  public void anExclusionByPatternIsNotGuessedAt() throws Exception {
    LintPolicyYamlWriter.addExclude(yaml(), "templates/**", null);

    assertFalse(LintPolicyYamlWriter.removeExclude(yaml(), "templates/load.hpl"));
    assertEquals(List.of("templates/**"), policy().getExcludes());
  }

  /** The linter refuses a suppression without a rule or a reason; so does the writer. */
  @Test
  public void incompleteSuppressionsAreRefused() {
    assertThrows(
        IOException.class,
        () -> LintPolicyYamlWriter.addSuppression(yaml(), null, null, null, "reason"));
    assertThrows(
        IOException.class,
        () -> LintPolicyYamlWriter.addSuppression(yaml(), "HOP-CHECK", null, null, " "));
    assertTrue(!new File(yaml().toString()).exists(), "nothing should have been written");
  }
}
