////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/coalesce/src/main/doc/coalesce.adoc
= Coleasce

== Description

Lets you combine multiple fields into one, selecting the first value that is non-null.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform. *Note*: This name has to be unique in a single pipeline.
|Considered empty string as null|The transform can consider empty string as null.
|===

== Fields
|Fields|specify the name, type, and value in the form of a string. Then, specify the formats to convert the value into the chosen data type.

[width="90%", options="header"]
|===
|Name|The result field name, can overwrite an existing one.
|Type|The formats to convert the value into the chosen data type.
|Remove|Remove input fields from the stream.
|Input fields|The order of the input fields listed in the columns determines the order in which they are evaluated.
|===

NOTE: Support MetaData Injection (MDI)