////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /technology/redis/
:language: en_US
:description: Apache Hop supports Redis through a connection metadata type and input/output transforms.

= Redis Technology

https://redis.io/[Redis] is an in-memory data structure store used as a database, cache and message broker.

== Redis Support in Hop

Hop supports Redis Standalone, Sentinel and Cluster topologies with the following:

=== Metadata Types

* xref:metadata-types/redis/redis-connection.adoc[Redis Connection]: Create a reusable Redis connection.

=== Pipeline Transforms

* xref:pipeline/transforms/redis-input.adoc[Redis Input]: Read STRING, HASH, SET or LIST values.
* xref:pipeline/transforms/redis-output.adoc[Redis Output]: Write STRING, HASH, SET or LIST values.

The Redis plugin is distributed as an optional marketplace technology plugin (`hop-tech-redis`).
