:documentationPath: /vfs/
:language: en_US

= Google Cloud Storage VFS

== Scheme

The scheme you can use to access your files in Google Cloud Storage is

`**gs://**`

== Configuration

You need to generate a key file for a service account to make it work.  Go to the Google Cloud console to do this. Once you have a key file for your service account, with permissions to access your GCP storage, point to it with either a system environment variable called `GOOGLE_APPLICATION_CREDENTIALS` (standard Google way of doing this) or in the Options dialog in the 'Google Cloud' tab. You can also use `hop-conf`:

[source,shell script]
----
      -gck, --google-cloud-service-account-key-file=<serviceAccountKeyFile>
                            Configure the path to a Google Cloud service account JSON key file
----

Once done you will see a `googleCloud` entry in the central `hop-config.json` file:

[source,json]
----
{
  "googleCloud" : {
    "serviceAccountKeyFile" : "/path/to/your/google-key.json"
  }
}
----

== Usage and testing

To test if the configuration works type use File/Open in the GUI and type in googledrive:// as a file location. Then hit enter (or click the refresh button).  Browse to a CSV, JSON or text file you uploaded and open it.  If all is configured correctly you should be able to see the content in the Hop GUI.


