////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[RemotePipelineEngine]]
:imagesdir: ../assets/images
= Remote Pipeline Engine

== Hop Remote pipeline engine

The remote run configuration runs pipelines on a remote Hop Server.

This run configuration requires little configuration, but has two prerequisites:

. a running xref:hop-server/index.adoc[Hop Server]
. a xref:metadata-types/hop-server.adoc[Hop Server metadata definition] in your project, pointing to your running Hop Server.

=== Options


[width="90%", options="header", cols="1,3"]
|===
|Option|Description
|Hop server|The remote Hop server to run this pipeline on.
|Run Configuration|The configuration to use on the remote Hop Server. In a lot of configurations, this will be a local (locally on the server) runtime configuration, but could be any other runtime configuration, e.g. a Spark runtime configuration that is started from a Spark cluster edge node
|Server poll delay (ms)|The delay in milliseconds between periodic polls to the remote server.
|Server poll interval (ms)|The interval in milliseconds between periodic polls to the remote server.
|===

