////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[LocalPipelineEngine]]
:imagesdir: ../assets/images
= Local Pipeline Engine

== Local

The local runner runs on the local Hop engine.


=== Options

[width="90%", options="header"]
|===
|Option|Description|Default
|Row set size|The row set buffer size.|10.000
|Safe mode|Checks every row passed through your pipeline and ensure all layouts are identical. If a row does not have the same layout as the first row, an error is generated and reported.|false
|Collect metrics|Collects metrics to monitor the performance of your pipeline.|false
|Sort transforms|Performs a https://en.wikipedia.org/wiki/Topological_sorting[topological sort] of the transforms in the pipeline before execution.|false
|Log rows feedback|Enables log rows feedback, showing a log line every after processing multiple of 50.000 (default) rows.|false
|Feedback size in rows|The number of rows to return as feedback.|50.000
|===

