////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/uniquerowsbyhashset/src/main/doc/uniquerowsbyhashset.adoc
= Unique Rows (HashSet)

== Description

The Unique Rows (HashSet) transform removes duplicate rows and filters only the unique rows as input data for the transform.

This transform differs from the Unique Rows pipeline transform by keeping track of the duplicate rows in memory and does not require a sorted input to process duplicate rows. 

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform Name|Name of the transform this name has to be unique in a single pipeline.
|Compare using stored row values|Select this option to store values for the selected fields in memory for every record. Storing row values requires more memory, but it prevents possible false positives if there are hash collisions.
|Redirect duplicate row|Select this option to process duplicate rows as an error and redirect them to the error stream of the transform. If you do not select this option, the duplicate rows are deleted.
|Error description|Specify the error handling description that displays when the transform detects duplicate rows. This description is only available when Redirect duplicate row is selected.
|Fields to compare table|	

Specify the field names for which you want to find unique values.

-OR-

Select Get to insert all the fields from the input stream. 
|===