////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/uniquerows/src/main/doc/uniquerows.adoc
= Unique Rows

== Description

The Unique rows transform removes duplicate rows from the input stream(s), input has to be sorted.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform Name|Name of the transform this name has to be unique in a single pipeline.
|Add counter to output?|Check this option to add a counter field to the stream.
|Counter field|Define the counter field name.
|Redirect duplicate row|Processes duplicate rows as an error and redirect rows to the error stream of the transform. Requires you to set error handling for this transform.
|Error Description|Sets the error handling description to display when duplicate rows are detected. Only available when Redirect duplicate row is checked.
|Fields to compare table|Specify the field names on which you want to force uniqueness or click Get to insert all fields from the input stream(s) You can choose to ignore case by setting the Ignore case flag to Y.
|===