////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /technology/arrow/
:language: en_US
:description: This page describes how Hop supports the Arrow data type.

= Arrow

From https://arrow.apache.org[arrow.apache.org]:

Apache Arrow™ is a data serialization system. To learn more about Arrow, please read the https://arrow.apache.org/docs/index.html[current documentation].

Hop supports Arrow through a number of plugins.
...

== Pipeline Transforms

* xref:pipeline/transforms/arrow-decode.adoc[Arrow Decode]: This allows you to extract Hop values from an Arrow Record data type.
* xref:pipeline/transforms/arrow-encode.adoc[Arrow Encode]: This allows you to extract Hop values from an Arrow Record data type.

|===
