////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

= Neo4j Graph Output

== Description

The Graph Output transform aims to allow input fields to be mapped automatically to a graph model. The model is for now defined locally but the goal is to have this done elsewhere in the near future. The algorithm used takes null values for fields mapped to primary properties of nodes into account and will not merge on these nodes and will not create or update relationships to it.

== Limitations

* Updates across unknown nodes `()--()` are not supported
* Circular relationships to the same nodes: please create a new node with a different name and the same label to make this work. It allows you to uniquely map input fields to these node properties and get the correct results.


== Notable options


|===
|Option |Description

|Model
|the model to map fields to


|Mapping
|Here you define the mappings

|===
