////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/syslog/src/main/doc/syslog.adoc

= Send Message to Syslog

== Description

The Send message to Syslog transform allows you to send message logging to another server. The link:http://en.wikipedia.org/wiki/Syslog[Syslog] standard permits separation of the software that generates messages from the system that stores them and the software that reports and analyzes them.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Server name / IP address|Defines the server name or IP address of the Syslog server.
|Server port|Defines the server port of the Syslog server, by default 514
|Facility\A facility level is used to specify what type of program is logging the message. This lets the configuration file specify that messages from different facilities will be handled differently. The list of facilities is defined by RFC 3164.
|Priority|Select your priority/severity level (defined by RFC 5424).
|Add hostname to message|Adds the hostname to the message.
|Add timestamp to message|Adds the timestamp to the message.
|Data pattern|Define the Date/Time format for the timestamp
|Message field name|Select the fieldname that has the message to send to the Syslog server
|===