////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/cubeinput/src/main/doc/cubeinput.adoc
= Cube input

== Description

The De-serialize from file transform, formerly known as Cube Input, reads rows of data from a binary Hop file containing rows and metadata.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform Name|Name of the transform; this name has to be unique in a single pipeline.
|Filename|The name of the Hop cube file to be generated.
|Limit|Allows you to limit the number of rows written to
|Size|the cube file. A value of zero (0) indicates no size limit (optional). 
|===