////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Hop Encrypt is a command line tool to encrypt (obfuscate) passwords for use in XML, password or Hop metadata files.Hop Gui is Hop’s visual development environment. You’ll spend a lot of time here in the various perspectives of Hop GUI.

= Hop GUI

Hop GUI is the visual integrated development environment (IDE) for Apache Hop.

== Usage

Hop GUI doesn't take any parameters or arguments. To start, just run `hop-gui.bat` on Window or `hop-gui.sh` on Linux and Mac OS.
