////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Hop Translator - Translate the Apache Hop GUI and CLI tools

include::../snippets/hop-tools/hop-translator.adoc[]

TIP: check the https://hop.apache.org/community/contribution-guides/translation-contribution-guide/[Translation Contribution Guide] if you want to find out more about translating Hop.

&nbsp; +

The example below starts the Hop Translator tool with the provided `translator.xml` file as the first parameter.

The second parameter is the path to your local version of the https://www.github.com/apache/hop[Apache Hop source code].

&nbsp; +

[tabs]
====

Windows::
+
--
[source,bash]
----
hop-translator.bat translator.xml <YOUR_PATH_TO_THE_HOP_CODE>
----

Expected output: the Hop Translator tool starts.
--

Linux, macOS::
+
--
[source,bash]
----
./hop-translator.sh translator.xml <YOUR_PATH_TO_THE_HOP_CODE>
----

Expected output: the Hop Translator tool starts.
