////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Hop Search is a command line tool to search for metadata in Hop or a Hop project.

= Hop Search

Hop Search is a command line tool to search for metadata in Hop or a Hop project.

== Usage

[source,bash]
----
Usage: <main class> [-hilx] [-e=<environmentOption>] [-j=<projectOption>]
                    <searchString>
      <searchString>         The string to search for
  -e, --environment=<environmentOption>
                             The name of the lifecycle environment to use
  -h, --help                 Displays this help message and quits.
  -i, --case-insensitive     Perform a case insensitive search
  -j, --project=<projectOption>
                             The name of the project to use
  -l, --print-locations      Print which locations are being looked at
  -x, --regular-expression   The specified search string is a regular expression
./hop-search.sh  9.08s user 0.44s system 338% cpu 2.808 total
----

== Options

[options="header",width="90%"]
|===
|Option|Description
|<searchString>|The string to search for
|-e|The name of the lifecycle environment to use
|-h|Displays this help message and quits.
|-i|Perform a case insensitive search
|-j|The name of the project to use
|-l|Print which locations are being looked at
|-x|The specified search string is a regular expression
|===

== Examples

Example command: search for the string 'json' (case insensitive) in the 'hop-samples' project.

Command: `./hop-search.sh -j hop-samples -i json `

Output:

[source,bash]
----
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : null : matching property value: Enhanced JSON - Generate complex nested structure from table
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : matching property value: EnhancedJsonOutput
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : matching property value: Enhanced JSON Output
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : pipeline transform property : jsonBloc
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : pipeline transform property : jsonPrittified (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : pipeline transform property : isJSONFragment (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : pipeline transform property : isJSONFragment (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Final Complex Data structure : pipeline transform property : isJSONFragment (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Intermediate Structures : matching property value: EnhancedJsonOutput
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Intermediate Structures : matching property value: Enhanced JSON Output
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Intermediate Structures : pipeline transform property : jsonPrittified (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : Intermediate Structures : pipeline transform property : isJSONFragment (Boolean)
<PROJECT_PATH>/samples/transforms/Enhanced JSON - Generate complex nested structure from table.hpl : null : matching property value: This sample gets a table of values and generate a complex nested structure as output
by looping over a predefined key. Second Enhanced JSON Transform als gets a JSON fragment produced
by furst Enhanced JSON Transform and use it as value of an attribute of the resulting final 
JSON stream.
----