////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/numberrange/src/main/doc/numberrange.adoc

= Number range

== Description

Create ranges based on numeric fields.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Input field|Designate the field that gets checked for the lower and upper boundaries.
|Output field|Designate the output field name that gets filled with the value depending of the input field.
|Default value|Value to return if there are no matches within the ranges specified.
|Ranges|Designated the upper and lower bound of a range.
|Lower Bound|Designated the minimum value of a range.
|Upper Bound|Designate the upper value of a range.
|Value|Designated a name for the value. 
|===