////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/setvalueconstant/src/main/doc/setvalueconstant.adoc

= Set field value to a constant

== Description

The Set field value to a constant transform replaces the value of a field with a constant that you define.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Use variable in constant|Select to use a variable replacement within a constant.
|Field|Specify the field that contains the value you want to replace.
|Replace by value|Specify the value that will replace the original field value specified.
|Conversion mask (Date)|Specify a date format for the replaced field. See Common Formats for information on common valid date formats you can use in this transform.
|Set empty string?|Specify Y to allow an empty string when the value is empty; otherwise, a null value is used.
|===


== Metadata Injection Support

All fields of this transform support metadata injection. You can use this transform with ETL Metadata Injection to pass metadata to your pipeline at runtime.