:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/normaliser/src/main/doc/normaliser.adoc

= Row Normaliser

== Description

The Row Normaliser transform converts the columns of an input stream into rows. You can use this transform to normalize repeating groups of columns.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Typefield|The name of the type field (product in the example above).
|Fields table a|
A list of the fields you want to normalize; you must set the following properties for each selected field:

* Fieldname: Name of the fields to normalize (Product A ? C in the example).
* Type: Give a string to classify the field (A, B or C in our example).
* New field: You can give one or more fields where the new value should transferred to (sales in our example).
|Get Fields|Click to retrieve a list of all fields coming in on the stream(s).
|===

== Metadata Injection Support

All fields of this transform support metadata injection. You can use this transform with ETL Metadata Injection to pass metadata to your pipeline at runtime.