////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/normaliser/src/main/doc/normaliser.adoc

= Row Normaliser

== Description

The Row Normaliser transform converts the columns of an input stream into rows. You can use this transform to normalize repeating groups of columns.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Typefield|The name of the type field (product in the example above).
|Fields table a|
A list of the fields you want to normalize; you must set the following properties for each selected field:

* Fieldname: Name of the fields to normalize (Product A ? C in the example).
* Type: Give a string to classify the field (A, B or C in our example).
* New field: You can give one or more fields where the new value should transferred to (sales in our example).
|Get Fields|Click to retrieve a list of all fields coming in on the stream(s).
|===

== Metadata Injection Support

All fields of this transform support metadata injection. You can use this transform with ETL Metadata Injection to pass metadata to your pipeline at runtime.