////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/deletefiles/src/main/doc/deletefiles.adoc
= Delete Files

== Description

This workflow action deletes a set of files.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Include Subfolders|Also delete the subfolders in the folder selection
|Copy previous results to args?|Enable this if the set of files comes from a previous workflow action (as part of the result files)
|File/Folder|The file or folder to delete
|Wildcard|The regular expression matching files to delete if the previous option is a folder.  For example to delete all files ending in .dat, the regular expression would be ".*\.dat$".  
|Files/Folders|The complete list of files/folders to delete 
|===