////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/constant/src/main/doc/constant.adoc
= Add Constants

== Description

The Add constant values transform is a simple and high performance way to add constant values to the stream.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform. *Note*: This name has to be unique in a single pipeline.
|Fields|specify the name, type, and value in the form of a string. Then, specify the formats to convert the value into the chosen data type.
|===