////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[DisableUiElements]]
= Customize the UI

== Disable UI elements

Apache Hop has a system to disable UI elements and perspective.
This could be useful for managed instances where the user should not have full control of Hop.

You can add the following file to the Hop Config location by default `/hop/config` or when used the  `HOP_CONFIG_FOLDER` environment variable.

Add the following file: +
disabledGuiElements.xml

[source,xml]
----
<!--
~ Licensed to the Apache Software Foundation (ASF) under one or more
~ contributor license agreements.  See the NOTICE file distributed with
~ this work for additional information regarding copyright ownership.
~ The ASF licenses this file to You under the Apache License, Version 2.0
~ (the "License"); you may not use this file except in compliance with
~ the License.  You may obtain a copy of the License at
~
~       http://www.apache.org/licenses/LICENSE-2.0
~
~ Unless required by applicable law or agreed to in writing, software
~ distributed under the License is distributed on an "AS IS" BASIS,
~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
~ See the License for the specific language governing permissions and
~ limitations under the License.
~
-->

<!--
This file can be used to add code snippets and strings that can not be executed.
Example to block calls using any System. methods:
<exclusions>
<exclusion>System.</exclusion>
</exclusions>
-->

<exclusions>
    <exclusion>200-HopMetadataPerspective</exclusion>
    <exclusion>toolbar-50000-environment-label</exclusion>
    <exclusion>HopGuiPipelineGraph-ToolBar-10010-Run</exclusion>
</exclusions>
----

For each element that needs to be disabled, you can add an extra `<exclusion>` line. The value equals the ID element used in `@GuiWidgetElement`, `@GuiToolbarElement` , `@GuiContextAction` or `@HopPerspectivePlugin` 


