////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[HopSearch]]
= Hop Search

== Description

Hop Run is a command line tool which allows you to search in your projects.
It's particularly useful if you're working on a remote server over a ssh connection and you need to find a certain value, setting, transform, action and so on.

The search will match names, keys, values, descriptions and so on.

== Options

|===
|Option |Description |Default value| Available for plugin

|`-j` or `--project`
|The name of the project you want to search in
|None or the configured default project when none is specified
|Projects

|`-e` or `--environment`
|The environment to search in
|None or the configured default environment when none is specified
|Projects

|`-h` or `--help`
|Print the help options
|None
|

|`-i` or `--case-insensitive`
|Perform a case insensitive search
|false
|

|`-x` or `--regular-expression`
|The specified search string is a (Java) https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html[regular expression]
|false
|

|`-l` or `--print-locations`
|Print which locations are being looked at
|false
|

|===
