# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

services:
  integration_test_opensearch:
    extends:
      file: integration-tests-base.yaml
      service: integration_test
    depends_on:
      opensearch:
        condition: service_healthy
    links:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9200"
      - "9600"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Jackal-97-Nether-Blue^
    healthcheck:
      test: curl -k -u admin:Jackal-97-Nether-Blue^ --silent --fail https://opensearch:9200/_cluster/health || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
