////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[ProjectAdvanced]]
:imagesdir: ../../../assets/images
:page-pagination:
:page-pagination-no-next:
:openvar: ${
:closevar: }
:description: The 2 main things that define a project are its name and its home folder. Projects and environments as such are defined in the central Hop configuration file hop-config.json. By default this file lives in the config/ folder of your Hop client distribution. You can change that folder by setting the HOP_CONFIG_FOLDER environment variable on your system.


= Advanced project and environment management

== Configuration files

=== Global Project Configuration

The 2 main things that define a project are its name and its home folder.
Projects and environments as such are defined in the central Hop configuration file `hop-config.json`.
By default this file lives in the `config/` folder of your Hop client distribution.
You can change that folder by setting the `HOP_CONFIG_FOLDER` environment variable on your system.

&nbsp; +

.projectsConfig
[%collapsible]
=====

In `hop-config.json`, you'll find a `"projectsConfig"` section.
By default it contains the following:

[source,json]
----
{
  "projectsConfig" : {
    "enabled" : true,
    "projectMandatory" : true,
    "environmentMandatory" : false,
    "defaultProject" : "default",
    "defaultEnvironment" : null,
    "standardParentProject" : "default",
    "standardProjectsFolder" : null,
    "projectConfigurations" : [ {
      "projectName" : "default",
      "projectHome" : "config/projects/default",
      "configFilename" : "project-config.json"
    }, {
      "projectName" : "samples",
      "projectHome" : "config/projects/samples",
      "configFilename" : "project-config.json"
    } ],
    "lifecycleEnvironments" : [ ],
    "projectLifecycles" : [ ]
  }
}
----

As you can see the standard Hop client distribution defines 2 projects: default and samples.

=====

&nbsp; +

=== Project Configuration

Every project has extra metadata and settings stored in a project configuration file called ```project-config.json```.  For the samples project this would be ```config/projects/samples/project-config.json```.

&nbsp; +

.project-config.json
[%collapsible]
=====

Let's take a look at it:

[source,json]
----
{
  "metadataBaseFolder" : "${PROJECT_HOME}/metadata",
  "unitTestsBasePath" : "${PROJECT_HOME}",
  "dataSetsCsvFolder" : "${PROJECT_HOME}/datasets",
  "enforcingExecutionInHome" : true,
  "parentProjectName" : "default",
  "parentProjectFolders" : [ {
    "folder" : "templates",
    "copyOnce" : true,
    "copyOnEnable" : false,
    "overwrite" : false,
    "exclusionWildcard" : ".*\\.tmp"
  } ],
  "config" : {
    "variables" : [ ]
  }
}
----

=====

&nbsp; +

==== Variables

You can define variables on a project level as well.
This makes it handy to reference things like input and output folders which are not sensitive to being checked into version control.

Hop also sets a few built-in project variables when a project is activated:

.Built-in project variables
[cols="30%,70%",options="header"]
|===
|Variable|Description
|`PROJECT_HOME`|Home folder of the active project
|`HOP_PROJECT_NAME`|Name of the active project
|`PARENT_PROJECT_HOME`|Home folder of the immediate parent project (empty if none)
|`PARENT_PROJECT_NAME`|Name of the immediate parent project (empty if none)
|===

Use the parent variables to reference shared assets without fragile relative paths, for example:

`{openvar}PARENT_PROJECT_HOME{closevar}/SHARED_PIPELINES/example.hpl`

==== Parent projects

As you can see from the project configuration file (`parentProjectName`), a project can have a parent from which it will inherit all the metadata objects as well as all the variables that are defined in it.
When a parent is configured, Hop also sets `{openvar}PARENT_PROJECT_HOME{closevar}` and `{openvar}PARENT_PROJECT_NAME{closevar}` so pipelines and environment config files can point into the parent project home (for example shared pipelines or secrets kept outside the child repository).

Optional `parentProjectFolders` entries copy files from those parent folders into the child project home.
Each entry can copy once (when the destination is empty), copy every time the project is enabled, overwrite existing files, and skip files with a Java regular expression wildcard.
The child's `project-config.json` and `.git` directories are never overwritten.
See xref:projects/projects-environments.adoc[Projects and Environments] for the Project Properties dialog.

=== Environment configuration

Hop enviroments and their home folders are stored in the hop configuration file 'hop-config.json'.
That file lives by default in the *config* folder of the Hop installation.
System property `HOP_CONFIG_FOLDER` can also be used to point to a different folder

&nbsp; +

.environmentConfig
[%collapsible]
=====

[source,json]
{
 "environmentConfig" : {
  "enabled" : true,
  "openingLastEnvironmentAtStartup" : true,
  "environmentConfigFilename" : "environment.json",
  "environmentFolders" : {
   "Project 1 - DEV" : "/projects/one/dev/",
   "Project 1 - UAT" : "/projects/one/uat/",
   "Project 1 - PRD" : "/projects/one/prd/",
   "Project 2 - DEV" : "/projects/two/dev/",
   "Project 2 - UAT" : "/projects/two/uat/",
   "Project 2 - PRD" : "/projects/two/prd/",
  }
}

=====

&nbsp; +

== Use a project without hop-config.json

You can run or open a project for a single process without adding it to `hop-config.json`.
Hop registers the project in memory, points metadata at `{openvar}PROJECT_HOME{closevar}/metadata`, and does not write the registration back to disk.

This is useful when the project is provided by another system (a checkout, a zip, a container mount) and you do not want to mutate the Hop configuration.

[source,bash]
----
hop --project-locations my-project=/path/to/project run -f pipeline.hpl -r local
hop --project-locations my-project=/path/to/project gui -j my-project -f pipeline.hpl
----

`--project-locations` (short `-pl`) accepts a comma-separated list of:

* `name=/path/to/folder`
* `name=/path/to/archive.zip` or `name=/path/to/archive.jar` (opened read-only through VFS)
* `name=/path/to/folder:custom-config.json` when the project file is not `project-config.json`
* a bare folder or archive (the project name is taken from the folder or archive name)

When more than one project is listed, Hop enables the leaf project (a child that references a parent).
Parent metadata is still inherited.

Optional environment files for that process:

[source,bash]
----
hop --project-locations edw=/data/edw --environments edw-prod=/data/edw-prod.json \
    run -e edw-prod -f load.hpl -r local
----

`--environments` uses `name=[project:]file1;file2`.
If the project name is omitted, Hop infers it from the registered projects.
`--environment-conf-files` (also `--environment-config-files`) adds extra variable files to the enabled project or environment.

`-im` / `--in-memory` keeps Hop configuration in memory even when you are not using `--project-locations`.
The same behaviour can be enabled with the `{openvar}HOP_CONFIG_IN_MEMORY{closevar}` system variable set to `Y`.

These options are available on the `hop` root command (so they apply before `run`, `gui`, `search`, and so on) and on the subcommands themselves (`hop run -pl ...`, `hop gui -pl ...`).

See xref:hop-tools/hop.adoc[hop], xref:hop-run/index.adoc[hop run] and xref:hop-tools/hop-gui.adoc[hop gui] for the full option lists.

== Command Line Project Configuration

In addition to the Hop Gui and configuration files, all aspects of and operations on projects and environments can be managed through the Hop Conf command line tool.

include::../hop-tools/hop-conf/hop-conf-projects.adoc[]

