////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/blockingtransform/src/main/doc/blockingtransform.adoc
= Blocking transform

== Description

The Blocking transform blocks all output until the very last row is received from the previous transform.

At that point, the last row is sent to the next transform or the complete input is sent off to the next transform. Use the Blocking transform for triggering plugins, stored procedures, Java scripts, ... or for synchronization purposes.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform; this name has to be unique in a single pipeline.
|Pass all rows?|Determines whether to pass one row or all rows
|Spool directory|The directory in which the temporary files are stored if needed; the default is the standard temporary directory for the system
|Spool-file prefix|Choose a recognizable prefix to identify the files when they appear in the temp directory
|Cache size|The more rows you can store in memory, the faster the transform works
|Compress spool files?|Compresses temporary files when they are needed 
|===