////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/tech/cassandra/src/main/doc/cassandra-input.adoc
:openvar: ${
:closevar: }

= Cassandra Input

The Cassandra Input transform reads data from a Cassandra table of an Apache Cassandra cluster using CQL (Cassandra Query Language) version 3.x.

== Options

|===
|Option |Description

|Cassandra connection
|Here you specify the name of the connection to use either as a fixed value or as a variable expression. There are buttons to the right of the input field to hel you manage the metadata.

|Transport max length
|Set an optional maximum object size that can be sent. Leaving it blank means that the default cluster value is used. (typically 16384000)

|Execute query for each incoming row?
|This will cause the query to be executed repeatedly: once per input row.

|CQL
|The Cassandra Query Language statement you want to use.  For more information on CQL, see https://docs.datastax.com/en/cql-oss/3.x/cql/cqlIntro.html[Introduction to Cassandra Query Language]

|===

