////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/tech/cassandra/src/main/doc/cassandra-exec-cql.adoc
:openvar: ${
:closevar: }

= Cassandra Exec CQL

This action allows you to execute one or more CassandraQL statements on a Cassandra cluster.
You can use it to create or drop keyspaces, tables, indexes and so on.
If all statements executed successfully the result will be true (success).

== Options

* Cassandra Connection: You can specify the name of the connection to use either as a fixed value or as a variable expression. There are buttons to the right of the input field to hel you manage the metadata.
* CQL Script: You can enter one or more CQL statements ending with a semi-colon on a new line.

== Example:

[source]
----
CREATE KEYSPACE IF NOT EXISTS hop
WITH replication = {'class':'SimpleStrategy', 'replication_factor' : 3}
;
----
