////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/closure/src/main/doc/closure.adoc
= Closure

== Description

This transform was created to allow you to generate a Reflexive Transitive Closure Table for Mondrian.  For more information on how a closure table can help Mondrian gain performance, go here
Technically, this transform reads all input rows in memory and calculates all possible parent-child relationships.  It attaches the distance (in levels) from parent to child.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|The name that uniquely identifies the transform.
|Parent ID field|The field name that contains the parent ID of the parent-child relationship.
|Child ID field|The field name that contains the child ID of the parent-child relationship.
|Distance field name|The name of the distance field that will be added to the output
|Root is zero|Check this box if the root of the parent-child tree is not empty (null) but zero (0) 
|===