////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Hop plugins is an external repository containing a collection of plugins that can be used with but can't or won't be shipped with Apache Hop: The https://github.com/project-hop/hop-plugins/

[[ExternalPlugins]]
= External Plugins

== Hop Plugins

The https://github.com/project-hop/hop-plugins/[Hop plugins^] repository contains a collection of plugins that can be used with but can't or won't be shipped with Apache Hop.

=== Actions

* Send information using syslog

=== Transforms

* Dropbox Input
* Dropbox Output
* Excel Output
* Google Analytics
* Google Sheets Input
* Google Sheets Output
* LDIF Input
* MQTT Input
* MQTT Output
* Send message to syslog

== Mark Hall

== Transforms

* https://github.com/m-a-hall/hop-cpython[CPython^]: The Hop CPython Project is a plugin for the Apache Hop platform which provides the ability to execute a python script (via the cpython environment) within the context of a pipeline.
* https://github.com/m-a-hall/hop-mi[Hop Machine Intelligence^]: The hop-mi project is a version of PMI (Plugin Machine Intelligence) for the Apache Hop platform.
It (initially) provides access to supervised machine learning algorithms from various underlying "engines".
Out of the box, hop-mi provides six engines: Weka, Python scikit-learn, R MLR, Spark MLlib, DL4j (deep learning) and KerasApplication (Keras zoo models backed by TensorFlow).
The following learning schemes are supported, and are available in most of the engines: decision tree classifier, decision tree regressor, gradient boosted trees, linear regression, logistic regression, naive Bayes, naive Bayes multinomial, naive Bayes incremental, random forest classifier, random forest regressor, support vector classifier, support vector regressor, multi-layer perceptrons and deep learning networks. hop-mi/PMI is designed to be extensible via the addition of new engines and algorithms.

