////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Add Filenames To Result action adds a set of files or folders to the result list of the workflow action.

= Add filenames to result

== Description

The `Add Filenames to result` action adds a set of files or folders to the result list of the workflow action.

This list of filenames can then be used in the various workflow actions all around.

== Options

[options="header"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Include subfolders|Include subfolders of the selected folders
|Copy previous results to args?|Passes the results of the previous action to the arguments of this action.
|Clear result filenames?|This option clears the list of result files (from previous workflow actions) before creating a new list.
|File/Folder|Specify the list of files or folders with wildcards (regular expressions) in this grid. +
You can add a different source/destination on each line.
|Wildcard (RegExp)|A regular expression wildcard to include file patterns in the list of file names.
|===

After specifying a folder and wildcard (regular expression), use the `Add` button to add your file/folder selection to the table. Use the `Delete` or `Edit` buttons to remove or edit selected lines in the table.