////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Check DB Connections workflow action verifies connectivity with one or several databases.

= Check Db connections

== Description

The `Check DB Connections` workflow action verifies connectivity with one or several databases.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Connection|List of connections.
// |Wait|After the connection was opened, wait x (s, min, hrs).
// |Units of Time|Specify the unit of measurement for the length of time to remain connected.
// |Get connections|Get available connects.
|===

The `Get connections` retrieves all of the available xref:metadata-types/rdbms-connection.adoc[Relational Database Connections] in the current project.

The `Delete` button deletes the selected database connection line from the `Connections` table.