////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/workflow/actions/deletefile/src/main/doc/deletefile.adoc
= Delete File

== Description

This workflow action deletes a file (empty or not).

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|File name|The name and path of the file to delete.
|Fail if file doesn't exist|The workflow action will follow the failure outgoing hop when the file to be deleted does not exist anymore and this option is switched on. The default is off. 
|===