////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: Build documentation of a Hop project

= Build documentation

== Description

This action builds documentation of your Hop files or project.

== Options

* The target folder in which you want your project documentation to end up in.
* Include notes?
* Include parameters?
* Include metadata?
* Generate HTML?
* Remove MarkDown after HTML is generated?

== Generating HTML from MarkDown

The links from the index are currently set to the .md.html files.
I ran the following command in the target folder to generate the HTML files:

[source,bash]
----
for i in $(find . -name '*.md') ; do echo "$i" && pandoc -s $i -c assets/styles.css -o $i.html ; done
----

