////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:openvar: ${
:closevar: }
:description: The Checks If Files Exist action verifies that the specified files exist. The action returns true (success) if all the listed files exist, false (fail) if any of those don't.

= Checks if files exist

== Description

The `Checks if files exist` action verifies that the specified files exist. The action returns `true` (success) if _all_ the listed files exist, `false` (fail) if _any_ of those don't.

You can point to individual files, or to folders and use regular-expression wildcards (including an exclude wildcard) to verify that matching files are present. Optionally include subfolders per file/folder entry when evaluating wildcards.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action. This name must be unique in a single workflow.
|Files/Folders|A table of files and folders to verify:

* *File/Folder*: the full path of a file or folder. You can use variables like `{openvar}PROJECT_HOME{closevar}` in the path.
* *Wildcard (RegExp)*: optional regular expression. When the path is a folder, at least one file matching this pattern must exist. When empty and no exclude wildcard is set, the action only checks that the path itself exists (file or folder).
* *Exclude wildcard (RegExp)*: optional regular expression. Files matching this pattern are ignored when evaluating a folder.
* *Include subfolders*: when set to `Y`, also look for matching files in subfolders of the specified folder.
|===
