////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The HTTP action retrieves a file from a Web server using the HTTP protocol.

= HTTP

== Description

The `HTTP` action retrieves a file from a Web server using the HTTP protocol.

This action could be used to access data on partner Web sites.

For example, the daily data export or daily list of customers is located at a specified Web site.

Also, SaaS providers may give you a URL to locate a report.

You can call that URL to retrieve an Excel file or zip file that contains the data.

Salesforce requires that you use SOAP APIs to retrieve data.

If HTTP traffic is too heavy in your corporate environment, you may choose to use a proxy server with HTTP authentication.

The proxy and the web server each keep their own credentials, so the ones you fill in for the server are never offered to the proxy operator.

== Options

=== General Tab

[options="header", width="90%, cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|REST connection|Optional.
The name of a xref:metadata-types/rest-connection.adoc[REST connection] that supplies the client for this action: the proxy, the credentials, the TLS settings and the timeouts.
When one is selected, the fields on the Authentication and Proxy tabs are not used, and the URL below may be a path that is resolved against the connection's base URL.
|URL|The HTTP URL of the file to retrieve, or the directory name to store an uploaded file to.
|Ignore SSL certificate check|If selected, all SSL certificate checks are ignored.
|Run for every result row?|Check this if you want to run this action for every row that was generated by a previous pipeline.
Use the "Copy rows to result".
If selected, an HTTP request will be made for each result.
Otherwise, the file is only retrieved once
|Input field which contains URL|If the "Run for every result row?" option is selected, the field specified here will determine the file URL for each row
|Input field which contains upload file name|If the "Run for every result row?" option is selected, the field specified here will determine the local file that will be uploaded to the URL associated with the "Input field which contains URL" field.
|Input field which contains destination file name|If the "Run for every result row?" option is selected, the field specified here will determine the local file where the result downloaded from the URL associated with the "Input field which contains URL" field.
|===

=== Authentication Tab

These credentials belong to the web server the URL points at.
They are sent to that server only: a proxy that asks for authentication of its own is answered with the proxy credentials on the Proxy tab, never with these.

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Username|If the site requires authentication, use this username to log in
|Password|If a username is defined, this is the password for it
|===

=== Proxy Tab

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Proxy host|The host name of a proxy server to route the request through.
Leave it empty to connect directly.
|Proxy port|If a proxy server is defined, this is the port number it listens on.
The default is 8080.
|Proxy username|The user name for a proxy that requires authentication.
|Proxy password|The password that goes with the proxy user name.
|Ignore proxy for hosts|Target hosts to reach directly instead of through the proxy.
Separate the entries with `\|` and use `*` as a wildcard, for example `localhost\|127.*\|*.internal.example.com`.
This may be useful when working on an intranet or VPN
|===

=== Upload Tab

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Upload file|If you are uploading a file, this is the local file that will be sent to the HTTP server
|===

=== Reply Tab

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Target file|If you are downloading a file, this is its name on your local filesystem
|Append to specified target file?|If selected, and if the target file already exists, Hop will append all new data to the end of the file
|Add date and time to file name?|If selected, the date and time of the HTTP request (in yyyMMdd_HHmmss format) will be added to the target filename
|Target file extension|If the previous option is selected, this field specifies the extension (letters after the dot) of the target filename
|Add filename to result filename|Any files that are copied will appear as a result from this action; shows a list of files that were copied in this action.
|Result variable|If specified, the HTTP reply body is stored in this workflow variable so later actions can use it.
When running for every result row, the last reply is stored.
|===

=== Headers Tab

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|#|Order that the header should be processed
|Name|The name of this HTTP header
|Value|The actual header value to pass
|===