////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Mail Validator action checks if an email address is valid or not.

= Mail Validator

== Description

The `Mail validator` action checks if an email address is valid.

When the check passes the success hop will be followed, otherwise it will go to the fail hop


== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Email address|The email address, or list (separated by spaces) that have to be checked.
2+|Settings
|SMTP check? a|By default, Apache Hop will only check email address structure (using regular expression).

If you want to perform a SMTP check, please select this option and fill Email sender (see after).

Hop will extract domain name from the supplied email address (to check) and will try to get all exchangers from the domain name. Each exchanger will be queried.
|Time out|In order to perform a SMTP check, Hop will open a socket on the target SMTP host.
Specify here the socket time out (by default 0).
|Email sender|If you select "SMTP check?" option, this field is mandatory.
Hop will need sender email address to query SMTP host.
|Default SMTP server|If you know which SMTP server to query, please specify it here, Hop will then query only this one.
|===