////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The SQL action executes one or more SQL scripts from this action's configuration or from a file.

= MongoDB QL

== Description

The `MongoDB QL` action executes one or more JSON instructions from this action's configuration or from a file.

This action can be used to execute administrative instructions on a Mongo Database.

You can execute more than one JSON instruction.

Any JSON Instruction that can be used inside MongoDB's runCommand(), can be executed by this action.

MongoDB documentation : https://www.mongodb.com/docs/manual/reference/command/

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|MongoDB Connection|The MongoDB connection to use.
|Use external file|Enable this option to load the JSON instructions from a file.
|Filename|The filename for the file with JSON instructions.
|Use variable substitution|Enables variables to be used in the Script.
|JSON|The JSON instructions to execute.
Multiple statements can be separated by comma.
|===

== Examples

Single instruction
[source,json]
----
{"create":"hop_collection"}
----

Multiple instructions
[source,json]
----
[
    {"create":"hop_collection"},
    {"drop": "hop_collection" }
]
----