////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Bulk load from MySQL into file action bulk loads data from MySQL into a file.

= Bulk load from MySQL into file

== Description

The `Bulk load from MySQL into file` action bulk loads data from a MySQL table into a file.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Connection|The database connection.
|Target schema|The target schema.
|Target File name|The target file.
|High Priority|The priority to load the file with.
|Type|OUTFILE, DUMPFILE
|Field separator|The field separator to use.
|Fields enclosed by|The field enclosure to use.
|Optionally enclosed|
|Lines terminated by|The line termination string to use.
|Names of columns|A comma separated list of columns to export
|Limit to the...first lines|Only export the first x number of rows
|If file exists a|The action to take when the target file already exists:

* Create new with unique name
* Do Nothing
* Fail (default)
|Add file to result filenames|Add the target file to the result filenames
|===
