////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Bulk load into MySQL action loads data from a text file into a MySQL table.

= Bulk load into MySQL

== Description

The `Bulk load into MySQL` action loads data from a text file into a MySQL table.

This action uses the MySQL https://dev.mysql.com/doc/refman/8.0/en/load-data.html[`LOAD DATA`] command.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Connection|The connection to the MySQL database to use.
|Target schema|The schema of the table to load.
|Target table name|The name of the table to load into.
|Source file name|The name of the file to load.
|Local|Check this if the file is local.
|Priority a|The priority to load the file with. The available options are:

* NORMAL (default): no priority is set on the `LOAD DATA` command
* LOW PRIORITY: With the LOW_PRIORITY modifier, execution of the LOAD DATA statement is delayed until no other clients are reading from the table. This affects only storage engines that use only table-level locking (such as MyISAM, MEMORY, and MERGE).
* CONCURRENT: With the CONCURRENT modifier and a MyISAM table that satisfies the condition for concurrent inserts (that is, it contains no free blocks in the middle), other threads can retrieve data from the table while LOAD DATA is executing. This modifier affects the performance of LOAD DATA a bit, even if no other thread is using the table at the same time.
|Fields terminated by|The field terminator to use.
|Fields enclosed by|The field enclosure to use.
|Fields escaped by|The escape character to use.
|Lines started by|The line start string to use.
|Lines terminated by|The line termination string to use.
|Fields|The fields to load, separated by comma (,).
|Replace data|Check this option if you want to replace the data in the target data.
|Ignore the first ... lines|Ignores the first ... lines in the text file.
|Add files to result|Check this option if you want to re-use the filename of the text file in a next workflow action.
|===
