////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Neo4j constraint action can be used to create or drop constraints on node or relationship properties in a Neo4j Graph

= Neo4j constraint

== Description

The `Neo4j constraint` action can be used to create or drop constraints on node or relationship properties in a Neo4j Graph

For similar operations on Neo4j indexes, check the xref:workflow/actions/neo4j-index.adoc[Neo4j index] action.

== Options

* Neo4j Connection : The name of the Neo4j connection to update indexes on
* Constraint updates to perform: You can specify your list of constraint updates here
** Update type : CREATE or DROP
** Type of object to index on: NODE or RELATIONSHIP
** Type of constraint: UNIQUE, NOT_NULL, or NODE_KEY
** Constraint name: The name for your constraint (mandatory)
** Object name: the label of the node or relationship you want to update a constraint for
** Property: the property to put the constraint on (for NODE_KEY, use comma-separated properties like "id,name")

[NOTE]
====
NODE_KEY constraints are only available in Neo4j Enterprise Edition. NODE_KEY constraints require multiple properties (comma-separated) and can only be applied to nodes, not relationships.
====


