////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Neo4j Index action can be used to create or drop indexes on node or relationship properties in a Neo4j Graph

= Neo4j Index

== Description

The Neo4j Index action can be used to create or drop indexes on node or relationship properties in a Neo4j Graph

== Options

* Neo4j Connection : The name of the Neo4j connection to update indexes on
* Index updates to perform: You can specify your list of index updates here
** Update type : CREATE or DROP
** Type of object to index on: NODE or RELATIONSHIP
** Index name: optional but recommended name for your index
** Object name: the label of the node or relationship you want to update an index for
** Properties: the comma separated list of node or relationship properties to index


