////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Verify File Signature With PGP action can be used to verify a file signature to ensure its authenticity.

= Verify file signature with PGP

== Description

The `Verify file signature with PGP` action can be used to verify a file link:https://www.gnupg.org/gph/en/manual/x135.html[signature to ensure its authenticity].

GnuPG package must be installed in the runtime environment and encryption keys added to the runtime user keystore for this to function.


== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|GPG location|The file path of the GnuPG executable (e.g. `/usr/bin/gpg`).
|Filename|The signed file path.
|Use detached signature|Whether or not to use a detached signature.
|Detached signature|Path to the detached signature file (only available when the `Use detached signature` above is checked)
|===