////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/workflow/actions/ping/src/main/doc/ping.adoc
= Ping

== Description

The Ping action can be used to ping a host using the ICMP protocol. The result it true when the host is reachable, otherwise false.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Host name/IP|The name or the IP address of the host to ping
|Ping type|Classic ping: This calls the ping as a command line of the operating system. The result is true when no packets (defined in the "Nr. packets to send" option) are lost.
System ping: This option uses the Java implemented methods. The result is true when the host name can be resolved and the host is reachable within the given timeout period.
System ping then classic ping: try both options (first the system ping and when that fails, try the classic ping)
|Timeout (ms)|The timeout in ms when the system ping option is used.
|Nr. packets to send|The number of packets to send (by default 2, only used by the Classic ping option).
|===
