////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Repeat action repeats the pipeline or workflow of your choice until a certain condition is met.

= Repeat

== Description

The Repeat action repeats the pipeline or workflow of your choice until a certain condition is met.
The condition is either:

* A variable in the workflow is set or set to a certain value
* The End Repeat action is executed in the specified repeating workflow

In addition to the workflow and pipeline executor transforms, the Repeat and End Repeat actions let you build loops from a workflow. It requires a workflow or pipeline and a run configuration to use. The action will continue to execute the specified workflow or pipeline until a condition is met: either a variable is set or a variable set to an specific optional value, or an End repeat action is triggered in a child workflow.

TIP: If you use a variable name for the file to repeat, ensure a default parameter is set with a file extension so Hop knows if it is a pipeline or a workflow file.

== Example
The samples project example: ``/loops/repeat-action.hwf`` and ``child-check-set-counter-value.hpl`` runs a pipeline that increments a ${COUNTER} variable with each run. If the variable values exceeds 10, a variable ${END_LOOP} is set. This variable is detected by the Repeat action, and the loop stops. Because the Variable scope of COUNTER in the workflow is set to “Valid in the current workflow”, when you set COUNTER in the child the new value goes upstream.




== Options

[options="header"]
|===
|Option|Description

|Workflow action name|The name of the workflow action.

|File to repeat|The filename of the pipeline or workflow to execute repeatedly.

|Run configuration|The pipeline or workflow run configuration to use.

*Please note* that if you set a variable on a remote server the value is currently not reported back so only local workflow engines are currently supported.

|Stop repeating when this variable is set|Specify the variable you want to be checked before stopping the repeat loop

|Optional variable value| Only stop repeating when the above variable is set and contains this exact value

|Delay variable in seconds| Allow file execution to repeat using specified value in seconds

|Keep variable values after execution| This option keeps the variable values after a (repeating) pipeline or workflow execution to inject into the next iteration.

|Logging file|In this group you can specify if you want to log to a file and how that should be done

|Parameters/Variables to set|You can specify the values of any parameters or variables in this dialog.
The values can contain variables themselves which will be resolved before every iteration.
If the option ```Keep variable values after execution``` is set we evaluate the expression only once before the first execution of the file.

|===

