////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Send SNMP Trap action sends alert messages to a remote SNMP-enabled device.

= Send Snmp Trap

== Description

The `Send SNMP trap` action sends alert messages to a remote SNMP-enabled device.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
2+|Server
|Server name / IP address|The server host.
|Server port|The server port.
|OID|The object identifier.
|Test connection|Can be used to test the connection.
2+|Advanced
|Target type|Type of target: Community or User.
|Community string|A user id or password that allows access to a router's or other device's statistics.
|User|The username to connect to the server
|Passphrase|The password to connect to the server
|Engine ID|
|Retry|Number of retries.
|Timeout|Timeout in milliseconds
2+|Message
|Message|The message to send.
|===
