////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/workflow/actions/webserviceavailable/src/main/doc/webserviceavailable.adoc
= Check if Webservice is available

== Description

The Check if Webservice is available action checks if a given URL (e.g. a Webservice URL) is valid, can be connected and data can be read from. If it connects within the given timeout and data can be read, it returns 'true', otherwise 'false'. Further information of the failing reason can be found in the log as an error log action.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|URL|Specifies the URL to validate.
|Connect timeout (ms)|The connect timeout in ms. The value is depending on the quality of service of this URL and experiences.
|Read timeout (ms)|After connection, the workflow action tries to read data. This value gives the read timeout in ms. The value is depending on the quality of service of this URL and experiences.
|===
