////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The Check If XML File Is Well-Formed action verifies if one or more files contain well-formed (allowed) XML content.

= Check if XML file is well-formed

== Description

The `Check if XML file is well-formed action` verifies if one or more files contain well-formed (allowed) XML content.

== Options

=== General tab

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Include Subfolders|Option to move the content of sub-folders.
|Copy previous results to args|Check this to pass the results of the previous action into the arguments of this action.
|File/Folder source|Enter or select (Browse button) a file or folder
|Wildcard (RegExp)|A regular expression wildcard for the filename pattern
|Files/Folders a|Specify the list of files or folders with wildcards (regular expressions) in this grid.
You can add a different source/destination on each line.

NOTE: You can use the Add button to add a line to the Files/Folders list.
|===

=== Advanced tab

In this tab you can specify the files and/or folders to move.

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
2+|Success On
|Success on|Allows you to set specific success conditions: Success if all files are well formed, Success if at least x files are well formed, or Success when number of bad formed files less than.
|Result files name|Specify which kind of filenames to add to the internal result file names: all filenames, only well formed filenames, or only bad filenames.
2+|Result file names
|Add filename a|Add the checked XML filenames to the workflow action result. The available options are:

* Add all filenames
* Add only well-formed filenames
* Add only bad-formed filenames
|===