////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:description: The XSD validator action performs an XSD validation against data in a file or in an input field.

= XSD validator

== Description

The `XSD validator` validates an XML files against an internal (defined in the XML file) or external (defined in a separate xsd file) XML schema.

XSD is short for link:http://en.wikipedia.org/wiki/XML_Schema_(W3C)[XML Schema] Definition.

As such, there are 2 entities at work here:

* The XML you want to validate the layout for
* The XSD (Schema) file that describes what the XML file should look like.

See also the xref:pipeline/transforms/xsdvalidator.adoc[XSD Validator pipeline transform].

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Enable external entity for XSD validation a|

Allow the XSD validation to resolve external references (XXE). Unchecked by default, which has three effects:

* A `DOCTYPE` declaration or an external entity in the XML being validated is refused and the action fails.
* XSD sources *none (default)* and *is defined inside XML* do not work: the `xsi:schemaLocation` / `xsi:noNamespaceSchemaLocation` reference is not resolved, not even when it points at a local file. Both options need the checkbox.
* A schema that pulls in another schema over the network with `xs:include` or `xs:import` (for example the W3C `xml.xsd`) needs the checkbox. Local file and relative includes keep working without it.

Only check this when the XML documents and the schemas you validate against are trusted. The default for new actions can be changed with the `ALLOW_EXTERNAL_ENTITIES_FOR_XSD_VALIDATION` Java system property.

|XSD Source a|The options are

* none (default) - requires *Enable external entity for XSD validation*
* is a file, let me specify filename
* is defined inside XML - requires *Enable external entity for XSD validation*
|XML File name|The name of the XML file
|XSD File name|The name of the XSD file
|===
