////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[BestPractices]]
:imagesdir: ../assets/images
:description: Apache Hop (Incubating) best practices are a set of guiding principles. These best practices apply to the way you design, run, test, deploy and maintain Hop project.

= Best practices

== Introduction

Apache Hop gives you a large amount of freedom when deciding how to do the things you want to do.
This freedom means you can be creative and productive in arriving at the desired outcome.
So please consider the advice given on this page as tips or free advice to be taken or rejected for a particular situation.
Only you can decide what the advice is worth.

== Naming

include::../snippets/best-practices/naming-conventions.adoc[]

== Size matters

include::../snippets/best-practices/size-matters.adoc[]

== Variables

include::../snippets/best-practices/variables.adoc[]

== Logging

include::../snippets/best-practices/logging.adoc[]

== Mappings

include::../snippets/best-practices/mappings.adoc[]

== Metadata Injection

include::../snippets/best-practices/metadata-injection.adoc[]

== Performance basics

include::../snippets/best-practices/performance-basics.adoc[]

== Governance

include::../snippets/best-practices/governance.adoc[]

== Loops

include::../snippets/best-practices/loops.adoc[]



