////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[HopAndKettle]]
:imagesdir: ../assets/images
:page-pagination:
:page-pagination-no-back:

= Hop vs Kettle

Hop initially (late 2019) started as a fork of the Kettle (Pentaho Data Integration).

Hop and Kettle/PDI are independent projects, each with their own roadmap and priorities.
Given these different roadmaps, architectural vision and development track, Hop and Kettle/PDI are incompatible.

However, since Hop shares a common history with Kettle/PDI, we provide the Hop community a way to import existing PDI/Kettle projects into Hop as seamlessly as possible.

Check the following pages to find out more:

* xref:hop-vs-kettle/hop-vs-kettle.adoc[Hop vs Kettle]: a comparison between the concepts and approaches in Kettle/PDI vs Hop
* xref:hop-vs-kettle/if-you-know-kettle.adoc[If you know Kettle] provides guidance on how to get started with Hop quickly if you've used Kettle/PDI before
* xref:hop-vs-kettle/import-kettle-projects.adoc[Import Kettle] explains how your existing Kettle/PDI projects can be imported into Hop
