////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/detectemptystream/src/main/doc/detectemptystream.adoc
= Detect Empty Stream

== Description

This transform will output one row if input stream is empty (ie when input stream does not contain any row). The output row will have the same fields as the input row, but all field values will be empty (null).

If the input stream is not empty it will not output anything.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform. This name must be unique throughout the pipeline.
|===

