/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.core.util;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileAttribute;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.Set;

/**
 * Creates temporary files that only the current user can read or write.
 *
 * <p>The JVM default temporary directory is a publicly writable one ({@code /tmp} and friends), so
 * a file created there with the platform default permissions can be read by every local account.
 * Hop stages metadata, project packages and payloads in temporary files and those can carry
 * credentials, so they are created with owner-only permissions instead.
 */
public class TempFileUtil {

  private static final FileAttribute<Set<PosixFilePermission>> OWNER_ONLY =
      PosixFilePermissions.asFileAttribute(PosixFilePermissions.fromString("rw-------"));

  private static final boolean POSIX =
      FileSystems.getDefault().supportedFileAttributeViews().contains("posix");

  private TempFileUtil() {
    // Static class
  }

  /**
   * Creates an empty temporary file in the default temporary directory, readable and writable by
   * the current user only. The file name is generated by the JVM and is not predictable.
   *
   * @param prefix the prefix of the generated file name
   * @param suffix the suffix of the generated file name, {@code .tmp} is used when null
   * @return the path of the newly created file
   * @throws IOException in case the file could not be created
   */
  @SuppressWarnings("java:S5443") // the permissions below are exactly what makes this safe
  public static Path createTempFile(String prefix, String suffix) throws IOException {
    if (POSIX) {
      return Files.createTempFile(prefix, suffix, OWNER_ONLY);
    }
    // No POSIX permissions available: drop all access first, then hand it back to the owner.
    File file = Files.createTempFile(prefix, suffix).toFile();
    file.setReadable(false, false);
    file.setWritable(false, false);
    file.setExecutable(false, false);
    file.setReadable(true, true);
    file.setWritable(true, true);
    return file.toPath();
  }

  /**
   * The {@link File} flavour of {@link #createTempFile(String, String)}, for callers that work with
   * the {@code java.io} API.
   *
   * @param prefix the prefix of the generated file name
   * @param suffix the suffix of the generated file name, {@code .tmp} is used when null
   * @return the newly created file
   * @throws IOException in case the file could not be created
   */
  public static File createTempFileObject(String prefix, String suffix) throws IOException {
    return createTempFile(prefix, suffix).toFile();
  }
}
