////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

:documentationPath: /vfs/
:language: en_US

= Azure Storage

== Scheme

The scheme you can use to access your files in Azure Blob Storage is

`**azure://**`

== Configuration

To get access to your Azure storage files you need to configure a few things:

* The name of your storage account in Azure
* The key of your storage account in Azure

You can find both in the Storage Accounts section of your Azure portal.

* A file block size : This needs to be a multiple of 512 bytes.

All 3 options can be set in either the Hop GUI options dialog (Menu: Tools / Options) or using the following Hop Conf (`hop-conf.sh` or `hop-conf.bat`) command line options:

[source,shell script]
----
      -aza, --azure-account=<account>
                            The account to use for the Azure VFS
      -azi, --azure-block-increment=<blockIncrement>
                            The block increment size for new files on Azure,
                              multiples of 512 only.
      -azk, --azure-key=<key>
                            The key to use for the Azure VFS

----

Once done you will see an `azure` entry in the central `hop-config.json` file:

[source,json]
----
{
  "azure" : {
    "account" : "storage-account-name",
    "key" : "a/key-comprised-of-a-long-set-of-characters-and-numbers==",
    "blockIncrement" : "1024"
  }
}
----

== Usage and testing

To test if the configuration works you can simply upload a small CSV file in an Azure Storage folder and then use File/Open in Hop GUI.  Then you type in `azure://` as a file location and hit enter (or click the refresh button).  Browse to the CSV file you uploaded and open it.  If all is configured correctly you should be able to see the content in the Hop GUI.



