////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /technology/google/
:language: en_US

= Google Technology

== Introduction

The Google technology stack is supported in Hop through a number of plugins.  We briefly touch upon them below.

=== Google Analytics

You can use the `Google Analytics` transform to get information from this service.

== Google Sheets

It can be very convenient to save data into a Google sheet or indeed to read from it.  You can do this using the `Google Sheets Input` and `Google Sheets Output` transforms.

== Google Drive

Hop has a Virtual File System (VFS) plugin for Google Drive.  For more information see the VFS section of the documentation.

== Google Cloud Storage

Hop has a Virtual File System (VFS) plugin for Google Cloud Storage.  For more information see the VFS section of the documentation.

