////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /technology/google/
:language: en_US
:description: The Google platform is supported in Hop through a number of (Beam) transforms and Apache VFS support for Google Drive and Google Cloud Storage. Additionally, a number of external transform plugins are available.

= Google Technology

== Introduction

The Google technology stack is supported in Hop through a number of plugins.
We briefly touch upon them below.

== Pipeline Transforms

* xref:pipeline/transforms/beambigqueryinput.adoc[BigQuery Input (Beam)]
* xref:pipeline/transforms/beambigqueryoutput.adoc[BigQuery Output (Beam)]
* xref:pipeline/transforms/beambigtableinput.adoc[Bigtable Input (Beam)]
* xref:pipeline/transforms/beambigtableinput.adoc[Bigtable Output (Beam)]
* xref:pipeline/transforms/beamgcppublisher.adoc[GCP Pub/Sub Publisher (Beam)]
* xref:pipeline/transforms/beamgcpsubscriber.adoc[GCP Pub/Sub Subscriber (Beam)]

Check the xref:plugins/external-plugins.adoc[external plugins] for more information on a number of additional Google plugins that can't be or won't be included with Apache Hop (Google Sheets Input and Output, Google Analytics)

== VFS

Apache xref:vfs.adoc[VFS Support] in Hop allows you to directly read from a multitude of file systems and protocols, including Google:

* xref:vfs/google-drive-vfs.adoc[Google Drive]: read and write data directly from and to Google Drive files and folders.
* xref:vfs/google-cloud-storage-vfs.adoc[Google Cloud Storage]: read and write data directly from and to files and folders in Google Cloud Storage buckets

== Beam vs Google Cloud

When executing your pipeline using a Beam runner which is NOT DataFlow, make sure to pass the default Google cloud project ID by running:

`gcloud config set project <project-id>`

This affects Google Cloud specific APIs like BigQuery, Pub/Sub and others.
