////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /technology/google/
:language: en_US

= Google Technology

== Introduction

The Google technology stack is supported in Hop through a number of plugins.  We briefly touch upon them below.

== Pipeline Transforms

== VFS

Apache xref:vfs.adoc[VFS Support] in Hop allows you to directly read from a multitude of file systems and protocols, including Google:

* xref:vfs/google-drive-vfs.adoc[Google Drive]: read and write data directly from and to Google Drive files and folders.
* xref:vfs/google-cloud-storage-vfs.adoc[Google Cloud Storage]: read and write data directly from and to files and folders in Google Cloud Storage buckets

