////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/filecompare/src/main/doc/filecompare.adoc
= File compare

== Description

You can use the File compare workflow action to compare the contents of 2 files and control the flow of the workflow by it. When the contents of the files are the same the success outgoing hop will be followed, else the failure hop will be followed.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action. This name has to be unique in a single workflow.
|File name 1|The name and path of the file of the first file to compare.
|File name 2|The name and path of the file of the second file to compare. 
|===