:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/edi2xml/src/main/doc/edi2xml.adoc
= Edi to XML

== Description

The Edi to Xml transform converts Edi message text (conforming to the ISO 9735 standard) to generic XML. The XML text is more accessible and allows for selective data extraction using XPath and the Get Data From XML transform. 

== Options

The transform configuration requires the field name containing the EDI text, and an output field name for the XML text. If the output field name is left empty, the EDI text is going to be replaced by the XML text.

The structure of the XML output follows the following pattern:

[source,xml]
----
<edifact>
	<SEGMENT>
		<element>
			<value></value>
			...
		</element>
		...
	</SEGMENT>
	...
</edifact>
----

The conversion rules are:

* the root of the document is the "edifact" tag
* each segment in the edifact message is converted to a tag, using the segment name as the tag name.
* each field within a segment is represented by an "element" tag
* each value within a field is represented by an "value" tag
