////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[Samples]]
= Samples

Hop comes with a set of samples for workflows, pipelines, actions, transforms and other metadata objects.

This `samples` project is included in your Hop installation in the `config/projects/samples` folder.
You can open individual sample workflows or pipelines, or add a xref:projects/index.adoc[Hop project], pointing the project's home directory to the `samples` folder.

The samples project is work in progress.
More samples will gradually be added until feature completeness.

The project's folder structure may change over time, but is intended to be self-explanatory: you'll find sample workflows and pipelines along with samples that have been organized in folder by action or transform name.
For example, the 'workflowexecutor' folder contains a workflow and pipeline that show how to use the workflow executor transform (to execute workflows) in a pipeline.

