////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/metastructure/src/main/doc/metastructure.adoc
= Metadata structure of stream

== Description

This transform produces as output the metadata of the input fields of this transform.
Before producing this output the transform reads and discards (or eats) all input rows.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Output row count|Include the number of rows eaten by this transform in the output
|Field for row count|The name of the field containing the number of rows eaten
|===
