////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-msacces]]
:documentationPath: /database/databases/
:language: en_US

= Microsoft Access

When creating new database connection, specify the database path to the .mdb or .accdb file in database name field. 

This database connection uses the UCanAccess driver which works well for reading with TableInput, DatabaseLookup, but it's not great for writing. 
For writing it is better to use the Microsoft Access Output transformation.


[cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | Included
|Version Included | 5.1.3
|Hop Dependencies | None
|Documentation | https://spannm.github.io/ucanaccess/10-ucanaccess.html[Documentation Link]
|JDBC Url | jdbc:ucanaccess://path.mdb
|Driver folder | <Hop Installation>/lib/jdbc
|===
