////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-hive]]
:documentationPath: /database/databases/
:language: en_US

= Apache Hive

== Features

[cols="2*",options="header"]
|===
| Feature | Info
|Type | Relational
|Driver | Included
|Version Included | 3.1.3
|Hop Dependencies | None
|Documentation | https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Clients#HiveServer2Clients-JDBC[Documentation Link]
|JDBC Url | jdbc:hive2://<host:port>,<host2:port2>/databaseName
|Driver folder | Hop Installation/plugins/databases/hive/lib
|===

== Partitions

Apache Hive need to have a PARTITION clause generated before the fields definition.
To do this you can add table and clause definitions in the specific Hive field called 'Table-partition clauses'.  This is the format to specify:

`TABLE1(CLAUSE1);SCHEMA2.TABLE2(CLAUSE2)`

For example, if you want to partition a `customers` table by `statecode` dynamically, you can add the following: `customers(statecode)` and for `INSERT INTO` statement Hop will add `PARTITION(statecode)`.


HINT: for dynamic partitioning you can add the following statements in the `advanced` tab of the RDBMS metadata as statements to run right after connecting:

[source,sql]
----
SET hive.exec.dynamic.partition = true;
SET hive.exec.dynamic.partition.mode = nonstrict;
----

