////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-cloudera-impala]]
:documentationPath: /database/databases/
:language: en_US

= Cloudera Impala

You can query data on Hadoop using the low latency Impala implementation of SQL.
For more information see https://docs.cloudera.com/runtime/7.2.18/impala-overview/topics/impala-overview.html[Apache Impala Overview]

Impala itself has become an Apache project which you can find at the https://impala.apache.org[Apache Impala Homepage].

Check the https://docs.cloudera.com/documentation/other/connectors/impala-jdbc/latest.html[documentation] to see how you can connect to Cloudera Impala using Kerberos security.  Set the required options in the Options tab of your relational database connection metadata:

* AllowSelfSignedCerts=1
* AuthMech=1
* KrbHostFQDN=`IMPALA HOSTNAME`
* KrbRealm=`Kerberos Realm`
* KrbServiceName=`Impala Service name`
* SSL=1
* principal=`Principal name`


[cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | Use Cloudera Impala Drivers.  You can https://www.cloudera.com/downloads/connectors/impala/jdbc/2-6-35.html[Download] the latest versions from the Cloudera website.
|Version Included | None
|Hop Dependencies | Cloudera Impala Database Plugin
|Documentation | https://docs.cloudera.com/documentation/other/connectors/impala-jdbc/latest.html[Documentation Link]
|JDBC Url | jdbc:impala://hostname:port;principal=principalName
|Driver folder | <Hop Installation>/lib/jdbc
|===
