////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-duckdb]]
:documentationPath: /database/databases/
:language: en_US

= DuckDB

DuckDB is an in-process SQL OLAP database management system.

As an in-process database, DuckDB is easy to configure: specify the path to your DuckDB filename as the database name, e.g. `<PATH_TO_YOUR_DUCKDB_FILE>/duckdb`.

One thing to remember is about how DuckDB manages concurrency. The things to remember are summarized below:

* Only one process at a time can both read and write to the database.
* Multiple processes can read from the database, but no processes can write. To set this behavior, remember to specify in the connection's options the property duckdb.read_only = true

For details, please refer to https://duckdb.org/docs/api/java[DuckDB Java API documentation].

[cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | https://search.maven.org/artifact/org.duckdb/duckdb_jdbc/1.3.2.1/jar[Driver Link]
|Version Included | 1.3.2.1
|Hop Dependencies | None
|Documentation | https://duckdb.org/docs/api/java.html
|JDBC Url | jdbc:duckdb: (in memory) or jdbc:duckdb:<FILE_PATH>
|Driver folder | <Hop Installation>/lib/jdbc
|===


