////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-googlebigquery]]
:documentationPath: /database/databases/
:language: en_US

= Google BigQuery

[cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | https://cloud.google.com/bigquery/providers/simba-drivers/[Driver Link]
|Version Included | None
|Hop Dependencies | None
|Documentation | https://www.simba.com/products/BigQuery/doc/JDBC_InstallGuide/content/jdbc/d-intro.htm[Documentation Link]
|JDBC Url | jdbc:bigquery://[Host]:[Port];ProjectId=[Project];OAuthType=[AuthValue]
|Driver folder | Hop Installation/plugins/databases/googlebigquery/lib
|===

The Simba driver is packaged as a .zip containing many jars. Only a subset of the jars included with the Driver are necessary to use Bigquery JDBC with Apache Hop. Furthermore, some of the jars may conflict with those packaged with Hop and *must* be excluded.

#### Simba Driver Jars to Exclude (These jars included in the Simba driver conflict with Hop libraries and must be excluded):
 grpc-alts-<VERSION>.jar
 grpc-api-<VERSION>.jar  
 grpc-core-<VERSION>.jar
 grpc-netty-shaded-<VERSION>.jar

#### Simba Driver Jars to Include* (Include only these jars for a minimal profile):
 api-common-<VERSION>.jar
 gax-<VERSION>.jar
 gax-grpc-<VERSION>.jar
 google-api-services-bigquery-v2-<VERSION>.jar
 GoogleBigQueryJDBC42.jar
 google-cloud-bigquerystorage-<VERSION>.jar
 grpc-google-cloud-bigquerystorage-v1-<VERSION>.jar
 grpc-google-cloud-bigquerystorage-v1beta1-<VERSION>.jar
 grpc-google-cloud-bigquerystorage-v1beta2-<VERSION>.jar
 proto-google-cloud-bigquerystorage-v1-<VERSION>.jar
 proto-google-cloud-bigquerystorage-v1beta1-<VERSION>.jar
 proto-google-cloud-bigquerystorage-v1beta2-<VERSION>.jar
 threetenbp-<VERSION>.jar

pass:[*] List may not be exhaustive


