////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-mssqlnqtive]]
:documentationPath: /database/databases/
:language: en_US

= MS SqlServer (Native)

[cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15[Driver Link]
|Version Included | None
|Hop Dependencies | None
|Documentation | https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15[Documentation Link]
|JDBC Url | jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]
|Driver folder | Hop Installation/plugins/databases/mssqlnative/lib
|===

= Integrated Authentication / Windows Based Authentication

The native Microsoft SQL JDBC driver ships with extra files that enables authentication using your current MS Windows credentials.
When you download the JDBC drivers from Microsoft's site and unzip them, there will be a directory structure like the following:

*sqljdbc_10.2.1.0_enu\sqljdbc_10.2_enu\auth\x64*  <- 64bit authentication support files.

*sqljdbc_10.2.1.0_enu\sqljdbc_10.2_enu\auth\x86*  <- 32bit authentication support files.

You would copy the file:

*sqljdbc_10.2.1.0_enu\sqljdbc_10.2_enu\auth\x64\mssql-jdbc_auth-10.2.1.x64.dll*

to

*hop\lib\mssql-jdbc_auth-10.2.1.x64.dll*

The JDBC driver itself *sqljdbc_10.2_enu\mssql-jdbc-10.2.1.jre11.jar* should be copied into
*\hop\plugins\databases\mssqlnative\lib*


There is no need to rename the DLL to sqljdbc_auth.dll or place it in other locations.
