////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[database-plugins-mysql]]
:documentationPath: /database/databases/
:language: en_US

= MySql

[width="90%",cols="2*",options="header"]
|===
| Option | Info
|Type | Relational
|Driver | https://dev.mysql.com/downloads/connector/j/[Drivere Link] (Use Platform Independent)
|Version Included | None
|Hop Dependencies | None
|Documentation | https://dev.mysql.com/doc/connector-j/8.0/en/[Documentation Link]
|JDBC Url | jdbc:mysql://hostname:33060/databaseName
|Driver folder | Hop Installation/plugins/databases/mysql/lib
|===

**Important:** When creating a connection for mysql make sure you select the correct "database type". +
The Mysql 8+ type will work for the current Drivers. If needed you can use the Mysql driver to use the old "org.gjt.mm.mysql.Driver" Driver path.