////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[Concepts]]
:imagesdir: ../assets/images
:description: Hop comes with a number of concepts: a variety of tools, a large number of metadata types, projects and enviromments. At the core of literally everything in Hop is metadata.

= Concepts

include::snippets/hop-tools/hop-tools.adoc[]

include::snippets/hop-concepts/item-types.adoc[]

include::snippets/hop-concepts/hop-projects-environments.adoc[]

== Metadata

include::snippets/hop-concepts/metadata.adoc[]

== Various

The following items are an alphabetically ordered list of concepts that are used throughout Hop and will be mentioned at various locations in the Hop tools and documentation.


Lazy Loading::
include::snippets/hop-concepts/lazy-loading.adoc[]
