////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[SupportedAndUnsupportedJVMs]]
:imagesdir: ../assets/images
:description: A list of supported and unsupported JVMs necessary to run apache Hop.

= Apache Hop supported and unsupported JVMs

== Overview

To run apache hop you need java JVM, with the amount of JVMs in the market and with more to come apache Hop can have issues running in certain JVMs.

This page covers what JVM we are giving support and the ones we have black listed.

TIP: Take a look at the xref:installation-configuration.adoc[Installation] page for full instruction in how to install and configure apache Hop.

== Supported JVMs

Apache Hop works well with these 64-bit java runtimes for version 11.

* https://www.java.com/[Oracle Java Runtime]
* https://www.microsoft.com/openjdk[Microsoft OpenJDK] (OpenJDK builds for Windows, MacOS and Linux).
* https://openjdk.java.net/install/[OpenJDK Java Runtime]

== Unsupported JVMs

The list below is all JVM that has been confirmed having issue with apache Hop.

* https://adoptium.net/[Adoptium]

Other Java Runtimes may work, so you may be pioneering. Feel free to open a https://hop.apache.org/community/tools/#jira[JIRA ticket] if you run into issues, but please mention your JRE and version.

