////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Microsoft Access Output allows you to create a new Access database file as an output in a pipeline.

= image:transforms/icons/accessoutput.svg[Access output transform Icon, role="image-doc-icon"] Microsoft Access Output

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Microsoft Access Output allows you to create a new Access database file as an output in a pipeline.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
Note: This name has to be unique in a single pipeline.
|The database filename|The file name of the database file to which you are connecting
|Create database|Enable to generate a new Access database file
|Target table|Specifies the table to which you want to output data 
|Create table|Enable to create a new table in the Access database 
|Commit size|Defines the commit size when outputting data 
|===