////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Add Constant Values transform is a simple and high performance way to add constant values to a pipeline stream.

= image:transforms/icons/constant.svg[Add Constants Icon ,role="image-doc-icon"] Add Constants

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Add Constant Values transform is a simple and high performance way to add constant values to a pipeline stream.
|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Single Threaded! image:check_mark.svg[Supported, 24]
!Native Spark! image:check_mark.svg[Supported, 24]
!Beam Spark! image:check_mark.svg[Supported, 24]
!Beam Flink! image:check_mark.svg[Supported, 24]
!Beam Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
*Note*: This name has to be unique in a single pipeline.
|Fields|Name, type and constant *Value* for each field to add.
The value is entered as a string and converted with the format metadata on the same row.
See <<fields-table>>.
|===

[[fields-table]]
== Fields

include::../../snippets/field-metadata/field-columns.adoc[]

[options="header"]
|===
|Column|Description
|Name|Name of the constant field added to every input row.
|Type|Hop data type of the constant.
See xref:concepts.adoc#data-types[Data types].
|===

IMPORTANT: *Value* is a *single* constant per field.
*Group* is the thousands separator, not a row group.