////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Apache Tika transform parses files in all sorts of formats and extracts the text content as well as the available metadata.

= image:transforms/icons/tika.svg[Apache Tika Icon, role="image-doc-icon"] Apache Tika

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Apache Tika transform parses files in all sorts of formats and extracts the text content as well as available metadata it can extract.
This transform uses the http://tika.apache.org[Apache Tika] libraries to do the parsing.

The extracted metadata is given in JSON format.
If you need specific pieces of information from this metadata, you can extract those with a xref:pipeline/transforms/jsoninput.adoc[JSON Input] transform.
|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description

|Transform name
|Name of the transform.
Note: This name has to be unique in a single pipeline.

|File tab
|Here you can specify which files will be read and examined.

|Content tab
|This tab has various content settings.
For example, you can specify the file encoding, output format and so on.

|Output fields tab
|On this tab you can simply type in the names of the fields you want in the output.

|===
