////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Avro File Input transform simply reads Avro records from one or more files. Each record is encapsulated in an Avro field, each value has its own Schema and record.

= Avro File Input

== Description

The Avro File Input transform simply reads Avro records from one or more files.

Each record is encapsulated in an Avro field, each value has its own Schema and record.

== Options

[width="90%",options="header"]
|===

|Option|Description

|Transform name
|Name of the transform.
Note: This name has to be unique in a single pipeline.

|Filename field
|Select the field which contains the filename(s) of the Avro files to read

|Avro output field name
|The name of the field which will contain the Avro records

|Maximum number of rows to read
|Specify a positive number to limit the amount of rows read from all files.

|===

== Metadata Injection Support

All fields of this transform support metadata injection.
