////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

= Beam Bigtable Output

== Description

The Beam Bigtable Output transform can be used to write data to a link:https://cloud.google.com/bigtable[Google Cloud Bigtable] table using the Beam execution engine.

== Options

[width="90%",options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Project ID|The Google Cloud project.
|Instance ID|The Bigtable instance ID.
|Table ID|The Bigtable ID.
|Key field|the field to use as the Bigtable table row key
|Columns to set: a|a list of the columns to write to the Bigtable table:

* name: the name (qualifier) for this column
* family: the family name for this column
* source field: the pipeline field to use for the column's values

|===