////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/engines/beam/src/main/doc/beambigqueryinput.adoc
= Beam BigQuery Input

== Description

The Beam BigQuery Input transform can be used to input data from link:https://cloud.google.com/bigquery[Google Cloud BigQuery] using the Beam execution engine.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Project ID|The Google Cloud project.
|Data set ID|The BigQuery dataset ID.
|Table ID|The BigQuery table ID.
|Query|The input query, blank means everything from the table.
|Return fields selection|A list of result fields.
|BQ Field name|The field name in the BigQuery table.
|Rename to... (optional)|The name to be given to a column.
|Hop data type|The field data type.
|===