////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Beam BigQuery Output transform can be used to write data to a BigQuery table using the Beam execution engine.

= image:transforms/icons/beam-bq-output.svg[Beam BigQuery Output Icon, role="image-doc-icon"] Beam BigQuery Output

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Beam BigQuery Output transform can be used to write data to a link:https://cloud.google.com/bigquery[BigQuery] table using the Beam execution engine.
|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:cross.svg[Not Supported, 24]
!Spark! image:check_mark.svg[Supported, 24]
!Flink! image:check_mark.svg[Supported, 24]
!Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Project ID|The Google Cloud Platform project.
|Data set ID|The BigQuery dataset ID.
|Table ID|The BigQuery table ID.
|Create table if needed|Whether or not to create the table if it does not exist. (default: true)
|Truncate table|Whether or not to truncate the table before inserting.
|Fail if the table is not empty|Throws an error if the table is not empty.
|===