////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Beam Bigtable Input transform can be used to input data from Google Cloud Bigtable using the Beam execution engine.

= image:transforms/icons/beam-gcp-bigtable-input.svg[Beam BigTable Input Icon, role="image-doc-icon"] Beam Bigtable Input

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Beam Bigtable Input transform can be used to input data from link:https://cloud.google.com/bigtable[Google Cloud Bigtable] using the Beam execution engine.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:cross.svg[Not Supported, 24]
!Spark! image:check_mark.svg[Supported, 24]
!Flink! image:check_mark.svg[Supported, 24]
!Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform, this name has to be unique in a single pipeline.
|Project ID|The Google Cloud project.
|Instance ID|The Bigtable instance ID.
|Table ID|The Bigtable ID.
| Output key field name   | Name of the output field where the key (row key) will be stored.
| Source columns to read  | Specify the columns to read from Bigtable in this table.
| Source column (qualifier) | The specific Bigtable column qualifier to read.
| Target Hop data type    | The data type for the corresponding field in Hop.
| Target field name       | The name of the target field in Hop where the column value will be stored.
|===