////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Change File Encoding transform changes a text file from one encoding to another.

= image:transforms/icons/changefileencoding.svg[Change file encoding transform Icon, role="image-doc-icon"] Change file encoding

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Change File Encoding transform changes a text file from one encoding to another.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

* Transform name : the name of the transform, unique in a pipeline
* Source file
** Filename field : the name of the input field which will carry the file names at runtime
** Source encoding: the encoding of the text files
** Add source filename to the result filenames?
: Check this if you want to add the source file(s) automatically to the files list of the result of the pipeline.
* Target file
** Target filename field: the name of the input field which will contain the target (output) file name at runtime
** Create parent folder: checking this field automatically creates the output folder specified in the target filename field.
** Target encoding: you can select the target encoding here
** Add target filename to the result filenames?
: Check this if you want to add the target file(s) automatically to the files list of the result of the pipeline.
