////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Coalesce transform lets you list multiple fields and returns the first non-null value.

= image:transforms/icons/coalesce.svg[Coalesce transform Icon, role="image-doc-icon"] Coalesce

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Coalesce transform lets you list multiple fields and returns the first non-null value.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
*Note*: This name has to be unique in a single pipeline.
|Considered empty string as null|The transform can consider empty string as null.
|===

== Fields
Pick a list of fields to evaluate and specify a field name and type for the field output.

[options="header"]
|===
|Option|Description
|Name|The result field name, can overwrite an existing one.
|Type|The formats to convert the value into the chosen data type.
|Remove|Remove input fields from the stream.
|Input fields|The order of the input fields listed in the columns determines the order in which they are evaluated.
|===

