////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/cubeoutput/src/main/doc/cubeoutput.adoc
= Cube output

== Description

The Serialize to file transform, formerly known as Cube File Output, stores rows of data in a binary format in a file. The binary format has an advantage over a text (flat) file because the content does not have to be parsed when read back. The metadata is stored in the file as well.

The Serialize to file transform supports a write-once access pattern, and does not support appending to existing files.