////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Data Set Input transform allows reading from a data set in a pipeline

= image:transforms/icons/dataset.svg[Data Set Input transform Icon, role="image-doc-icon"] Data Set Input

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Data Set Input transform allows you to read from a data set in a pipeline.  This allows you to use and re-use static data in a project in various places without having to resort to copy the information Data Grid transforms.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:check_mark.svg[Supported, 24]
!Flink! image:check_mark.svg[Supported, 24]
!Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

[width="90%, options="header"]
|===
|Transform name|The name of this transform
|Data Set Name|The name of the data set to read from
|===
