////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Data Stream Output transform writes to an IPC Data Stream.

= Data Stream Output

== Overview

The **Data Stream Output** transform writes rows from a Hop pipeline to a configured xref:/metadata-types/data-stream/data-stream.adoc[Data Stream].

It supports all available Data Stream implementations (Arrow File Stream, Arrow Random Access File, and Arrow Flight).

== Options

[cols="1,3"]
|===
| Option | Description

| *Data Stream* |
The name of the target xref:/metadata-types/data-stream/data-stream.adoc[Data Stream] to write to.
This is a dropdown that shows all defined Data Streams in the project.

|===

== Notes

* The transform will automatically use the implementation defined in the selected Data Stream (file-based or Flight).
* When using Arrow Flight, data is sent directly to the running Flight server using the stream name.

