////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Delay Row transform will wait the indicated timeout period before passing an input row to the next transform.

= image:transforms/icons/delay.svg[Delay Row transform Icon, role="image-doc-icon"] Delay row

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Delay Row transform will wait the indicated timeout period before passing an input row to the next transform.

Use this transform if you deliberately want to slow down your pipeline.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform. This name has to be unique in a single pipeline.
|Timeout|How long to delay. You can type a static value, use a variable, or pick a numeric field from the incoming stream. Values are interpreted together with the selected time scale. If the selected field is null or empty, the transform treats it as zero (no delay).
|Time scale|Select whether the timeout is expressed in milliseconds, seconds, minutes, or hours.
|Get time scale from field|Enable this option to pick the time scale from a field in the incoming stream.
|Time scale field|Field that contains the time scale value. Accepted values (case-insensitive) are: `ms`, `millisecond(s)`, `s`, `second(s)`, `m`, `minute(s)`, `h`, `hour(s)`. Empty values default to seconds.
|===