////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Detect language transform examine text to identify the language.

= image:transforms/icons/detectlanguage.svg[Detect language transform Icon, role="image-doc-icon"] Detect language

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Detect language transform examine text to identify the language.

https://github.com/pemistahl/lingua?tab=readme-ov-file#3-which-languages-are-supported[list of supported languages]

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Single Threaded! image:check_mark.svg[Supported, 24]
!Native Spark! image:check_mark.svg[Supported, 24]
!Beam Spark! image:question_mark.svg[Maybe Supported, 24]
!Beam Flink! image:question_mark.svg[Maybe Supported, 24]
!Beam Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
This name must be unique throughout the pipeline.
|===

== Installation

This transform is not part of the default Hop client.
Install it from the Marketplace perspective in Hop Gui (Detect language, category Transforms), or with the xref:hop-tools/hop-marketplace.adoc[marketplace command line]:

[source,bash]
----
./hop marketplace install hop-transform-detectlanguage
----

The https://github.com/pemistahl/lingua[Lingua] language models and https://fastutil.di.unimi.it/[fastutil] are bundled with the plugin, so no jars have to be downloaded by hand.
Because the language models are large, the plugin is around 100MB in size.
