////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Execution Information transform allows you to read or delete information from an execution information location.

= image:transforms/icons/execinfo.svg[Execution Information Icon, role="image-doc-icon", width=20%] Execution Information

[%noheader,cols="3a,1a",role="table-no-borders" ]
|===
|

== Description

The Execution Information transform allows you to read (or delete) information from an xref:metadata-types/execution-information-location.adoc[Execution Information Location].
Depending on which operation you select, different input options will be enabled.
The output of the transform will be different as well.
This means that this transform always needs input-rows in order to produce output.

**Example to delete 200 Execution Id’s:**
First use Generate rows to create your fields and values to use (children: Boolean = true) and (limit: Integer = 200). Then use a first transform to get the ids (Operation: Get execution IDs), and a second connected transform to delete them (Operation: Delete execution). Optionally you can also delete by other fields such as date and ID. It can take a while to query the Execution Information, so keep an eye on the Duration column.

| == Supported Engines
[%noheader,cols="2,1a",frame=none,role="table-supported-engines"]

!===
!Hop Engine! image:check_mark.svg[Supported,24]
!Spark! image:check_mark.svg[Maybe Supported,24]
!Flink! image:check_mark.svg[Maybe Supported,24]
!Dataflow! image:check_mark.svg[Maybe Supported,24]
!===

|===

== Options

[options="header"]
|===
|Option|Description

|Transform name
|Name of the transform; this name has to be unique in a single pipeline

|Execution Information Location
|Select the xref:metadata-types/execution-information-location.adoc[location] that you want to work with.

|Operation type
|Select the operation you want to perform.

|Execution ID field
|The input field that will contain the execution ID

|Execution parent ID field
|The input field that will contain the execution parent ID

|Execution name field
|The input field that will contain the execution name to look for

|Execution type field
|The input field that will contain the execution type to look for

|Include children field
|The input field that will contain the boolean which indicates to include children in the search

|Limit field
|The input field that will contain the limit with which to search

|===
