////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Execute Unit Tests transform fetches and executes the available unit tests for the current project.

= Execute Unit Tests

== Description

The Execute Unit Tests transform fetches and executes the available xref:pipeline/pipeline-unit-testing.adoc[unit tests] for the current project.

== Options

[width="90%",options="header"]
|===
|Option|Description
|Transform name|name for this transform
|Test name input field|name of a field to get the unit test name from to determine which transforms to execute.
This option is only available when the transform receives input.
|Type of tests to run|Development or Unit Test
|Pipeline output field name|the pipeline that is tested
|Unit test output field name|the unit test that is executed
|Data set output field name|the (golden) data set used for this test
|transform output field name|the transform that is used in this test
|Error output field name|error status (Y or N)
|Comment output field name|the comment or error message returned by the test
|===