////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Files From Result transform reads filenames and additional metadata that was added through the 'add filename to result' in other transforms.

= image:transforms/icons/filesfromresult.svg[Files from result transform Icon, role="image-doc-icon"] Files from result

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Files From Result transform reads filenames and additional metadata that were added through the 'add filename to result' in other transforms.

Every time a file gets processed, used or created in a pipeline or a workflow, the details of the file, the workflow action, the transform, etc. is captured and added to an internal result set when the option 'Add file names to result' is set, e.g. in a Text File Output transform.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:cross.svg[Not Supported, 24]
!Flink! image:cross.svg[Not Supported, 24]
!Dataflow! image:cross.svg[Not Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|The unique transform name within the pipeline
|===

== Output fields

[options="header"]
|===
|Field name|Type|Example
|type|String|Normal, Log, Error, Error-line, etc.
|filename|String|somefile.txt
|path|String|C:\Foo\Bar\somefile.txt
|parentorigin|String|Process files pipeline
|origin|String|Text File Input
|comment|String|Read by text file input
|timestamp|Date|2006-06-23 12:34:56
|===
