////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Get Files Row Count transform counts the number of rows in a file or set of files.

= image:transforms/icons/getfilesrowcount.svg[Get files Row Count transform Icon, role="image-doc-icon"] Get files Row Count

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Get Files Row Count transform counts the number of rows in a file or set of files.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

=== File tab

[options="header"]
|===
|Option|Description
|directory|
|Expression|
|File or|
|Filename(s)|
|Files|
|Preview|
|Regular|
|Rows|
|Selected
|Show|
|Transform name|
|===

=== Content tab

[options="header"]
|===
|Option|Description
|Rows Count|
|fieldname|
|Rows|
|Separator|
|type|
|Row|
|separator|
|Include|
|files count|
|in output?|
|Files Count|
|fieldname|
|===