////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The HTTP Client transform performs a simple call to a base URL with additional options.
:page-engines: Hop Engine=yes, Single Threaded=yes, Native Spark=yes, Beam Spark=maybe, Beam Flink=maybe, Beam Dataflow=maybe

= image:transforms/icons/http.svg[HTTP client transform Icon, role="image-doc-icon"] HTTP client

== Description

The HTTP Client transform performs a simple call to a base URL with additional options.

====
http://<URL>?param1=value1&amp;param2=value2&amp;param3..
====

The result is stored in a String field with the specified name.

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform; this name has to be unique in a single pipeline
|REST connection|Optional.
The name of a xref:metadata-types/rest-connection.adoc[REST connection] that supplies the client for this transform: the proxy, the credentials, the TLS settings and the timeouts.
When one is selected, those fields below are not used, and the URL may be a path that is resolved against the connection's base URL.
|URL|The base URL string
|Accept URL from field?|Enable this option if you want to get the URL from a previous transform.
Enabling this will also allow you to specify the name of the input field.
|URL field name|The name of the incoming field that contains the URL
|Connection timeout|
|Socket timeout|The number of seconds to wait if no data is returned from the server.
|Connection close wait time |
|Result fieldname|The name of the field to store results
|HTTP status code field name|The name of the field to store the HTTP response code (e.g. 200, 404)
|Response time (milliseconds) field name|The name of the field to store the response time
|Http Login|The username to be passed during HTTP (Basic) authentication
|HTTP Password|The password to be passed during HTTP (Basic) authentication
|Proxy Host|The hostname of the Proxy Server to be used
|Proxy Port|The port number of the Proxy Server to be used
|Proxy username|The user name for a proxy that requires authentication.
The credentials of the web server are never offered to the proxy, and vice versa.
|Proxy password|The password that goes with the proxy user name.
|Ignore proxy for hosts|Target hosts to reach directly instead of through the proxy.
Separate the entries with `\|` and use `*` as a wildcard, for example `localhost\|127.*\|*.internal.example.com`.
|Parameters|Area where you define the parameter name-value pairs to pass on the URL
|Custom HTTP Headers|Area where you define optional HTTP headers
|===

== FAQ

=== The HTTP client transform doesn't do anything

*Q*: The HTTP client transform doesn't do anything, how do I make it work?

*A*: The HTTP client transform needs to be triggered.
Use a Row generator transform generating e.g. 1 empty row and link that with a hop to the HTTP client transform.

=== The HTTP client transform and SOAP

*Q*: Does the HTTP client support SOAP?

*A*: No, it just calls an URL with arguments.
Future transforms may provide SOAP functionality, Work is underway on a WebService transform supporting WSDL.
