////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Injector transform is used for special purpose pipelines where you want to 'inject' rows into a pipeline.
:page-engines: Hop Engine=yes, Single Threaded=yes, Native Spark=no, Beam Spark=no, Beam Flink=no, Beam Dataflow=no

= image:transforms/icons/injector.svg[Injector transform Icon, role="image-doc-icon"] Injector

== Description

The Injector transform is used for special purpose pipelines where you  want to 'inject' rows into the pipeline using the Hop API and Java, or from streaming input transforms like the xref:pipeline/transforms/kafkaconsumer.adoc[Kafka consumer] transform.

Among other things you can build 'headless' pipelines with it: pipelines that have no input at design time: do not read from file or database.

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Fieldname|Specify the field name of the rows to inject.
|Type|Specify the type of data.
|Length|For Number: Total number of significant figures in a number; For String: total length of string; For Date: length of printed output of the string.
See xref:pipeline/formatting-values.adoc[Formatting numbers and dates].
|Precision|For Number: Number of floating point digits; For String, Date, Boolean: unused.
|===