////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

= Kafka Producer

== Description

The Kafka Producer allows you to publish messages in near-real-time across worker nodes where multiple, subscribed members have access.
A Kafka Producer transform publishes a stream of records to one Kafka topic.

== Options

[width="90%",options="header"]
|===
|Option|Description
|Transform name|the name for this transform
|===

=== Setup

[width="90%",options="header"]
|===
|Option|Description
|Transform name|the name for this transform
|===

[width="90%",options="header"]
|===
|Option|Description
|Bootstrap servers|comma separated list of bootstrap servers in a Kafka cluster
|Client ID|The unique Client identifier, used to identify and set up a durable connection path to the server to make requests and to distinguish between different clients.
|Topic|The category to which records are published.
|Key Field|In Kafka, all messages can be keyed, allowing for messages to be distributed to partitions based on their keys in a default routing scheme.
If no key is present, messages are randomly distributed to partitions.
|Message Field|The individual record contained in a topic.
|===

=== Options

=== Options

Use this tab to configure the property formats of the Kafka consumer broker sources.
A few of the most common property formats have been included for your convenience.
You can enter any desired Kafka property.
For further information on these input names, see the Apache Kafka documentation site: https://kafka.apache.org/documentation/.

The options that are included by default are:

[width="90%",options="header"]
|===
|NName|Value
|auto.offset.reset|latest
|ssl.key.password|
|ssl.keystore.location|
|ssl.keystore.password|
|ssl.truststore.location|
|ssl.truststore.password|
|===

