////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Mapping Input transform represents and describes the input for a Mapping pipeline (referred to as a Mapping).

= image:transforms/icons/MPI.svg[Mapping Input Icon, role="image-doc-icon"] Mapping Input

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Mapping Input transform represents and describes the input for a Mapping pipeline (referred to as a Mapping).

The data of this input will be provided by the parent pipeline (the pipeline that calls the mapping).

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:check_mark.svg[Supported, 24]
!Flink! image:check_mark.svg[Supported, 24]
!Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

The fields described in this transform are those that you want to refer to in this pipeline.
When you use the mapping you can map input to these field names to arrive at a re-usable part of a pipeline.
