////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Merge Join transform performs a classic merge join between data sets with data coming from two different input transforms.

= image:transforms/icons/mergejoin.svg[Merge Join transform Icon, role="image-doc-icon"] Merge Join

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Merge Join transform performs a classic merge join between data sets with data coming from two different input transforms.

This transform assumes your data is sorted on the join keys. Use xref:pipeline/transforms/sort.adoc[Sort Rows] transforms on the incoming streams to enforce sorting if necessary.

Join options include INNER, LEFT OUTER, RIGHT OUTER, and FULL OUTER.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:check_mark.svg[Supported, 24]
!Flink! image:check_mark.svg[Supported, 24]
!Dataflow! image:check_mark.svg[Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|First Transform | The first transform to read data from (left hand side of the join)
|Second Transform | The second transform to read data from (right hand side of the join)
|Join type | The join type that should be used; INNER, LEFT OUTER, RIGHT OUTER, and FULL OUTER
|Key Field | The fields used for the join key, this only supports equal joins (key first transform = key second transform)
|===

For guidance on preventing deadlocks when using the Merge Join transform, refer to this how-to guide: 
**xref:how-to-guides/avoiding-deadlocks.adoc[Avoiding deadlocks]**
