////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

= Metadata Input

== Description

This transform gives you access to the Hop Metadata.
It outputs all the metadata objects of all types unless one or more types are filtered.

== Options

You can specify the field names of the information you need, or not.
You can also specify one or more type filters to limit the output of the transform.
For example, you can select filter 'rdbms' to only see the relational database connection metadata in the output.
