////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Multiway Merge Join transform joins input data from multiple streams.
:page-engines: Hop Engine=yes, Single Threaded=yes, Native Spark=no, Beam Spark=no, Beam Flink=no, Beam Dataflow=no

= image:transforms/icons/multimergejoin.svg[Multiway Merge Join transform Icon, role="image-doc-icon"] Multiway Merge Join

== Description

The Multiway Merge Join transform joins input data from multiple streams.

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Join Type|Type of join (INNER or FULL OUTER).
|===
