////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

= Neo4j Get Logging Info

This transform queries the Neo4j logging graph and retrieves logging information.

This transform uses the `NEO4J_LOGGING_CONNECTION`. Check the xref:hop-gui/perspective-neo4j.adoc[Neo4j perspective] for more details.

== Options

[options="header", width="90%"]
|===
|Option|Description
|Transform name|the name for this transform in your pipeline
|startOfPipelineDelta|Start of the date range for the given pipeline
|endOfPipelineDelta|End of the data range for the given pipeline
|startOfWorkflowDelta|Start of the date range for the given workflow
|endOfWorkflowDelta|End of the date range for the given workflow
|===