////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/randomvalue/src/main/doc/randomvalue.adoc
= Generate Random Value

== Description

This transform generates random numbers, integers, strings and even UUID.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Type a|The type of data you want to get back:

* Random number : generates a random number between 0 and 1
* Random integer : generates a random 32-bit integer
* Random string : generates a random string based on a 64-bit long random value
* Universally Unique Identifier (UUID)
* Universally Unique Identifier type 4 (UUID4)
* Random Message Authentication Code (HmacMD5)
* Random Message Authentication Code (HmacSHA1)

|===
