////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The REST Client transform enables you to consume RESTful services.

= image:transforms/icons/rest.svg[REST Client transform Icon, role="image-doc-icon"] REST Client

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The REST Client transform enables you to consume RESTfull services. Representational State Transfer (REST) is a key design idiom that embraces a stateless client-server architecture in which the web services are viewed as resources and can be identified by their URLs.

The REST client transform can use a pre-defined xref:metadata-types/rest-connection.adoc[REST connection] or use full URLs directly. +
When using a REST connection, the URL (hard-coded or accepted from a field) will be considered a path relative to the base URL defined in the REST connection. Header values that are specified in the `Headers` tab of the transform will overwrite any headers with the same name that were defined in the REST connection.

When used without a REST connection, the full URL needs to be specified.

== Example
The REST client Transform returns a "result" field (can change the name), and the field is often used in the next transform. For example, it can be read in by a JSON input transform that extracts the fields specified on the Fields tab.


|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

=== General Tab

The General tab is where you enter basic connection information for accessing a resource.

[options="header"]
|===
|Option|Description
|Transform name|Name of this transform as it appears in the pipeline workspace
|REST Connection|The (optional) xref:metadata-types/rest-connection.adoc[REST connection] to use for the base URL and authentication/authorization header name and value.
|URL|Indicates the path to a resource
|Accept URL from field|Designates the path to a resource is defined from a field
|URL field name|Indicates the field from which the path to a resource is defined
|HTTP method|Indicates how the transform interacts with a resource---options are either GET, PUT, DELETE, POST, HEAD, or OPTIONS
|Get Method from field|Designates the GET method is defined from a field
|Method fieldname|Indicates the field from which the GET method is defined
|Body field|Contains the request body for POST, PUT, and DELETE methods. Body field only accepts a previous field, not a hard coded value.
|Application type|Designates what type of application a resource is---options are either TEXT PLAIN, XML, JSON, OCTET STREAM, XHTML, FORM URLENCODED, ATOM XML, SVG XML, or TEXT XML
|Connection timeout|Indicates the timeout until a connection is established (milliseconds)
|Read timeout|Indicates the timeout for waiting for reading data (milliseconds)
|Result fieldname|Designates the name of the result output field
|HTTP status code fieldname|Designates the name of the HTTP status code field
|Response time (milliseconds) fieldname|Designates the name of the response time field
|===

=== Authentication Tab

If necessary, enter authentication details for a resource in the Authentication tab.

TIP: Hop allows using NULL parameters/variables for both the HTTP Login and HTTP Password.

[options="header"]
|===
|Option|Description
|HTTP Login|Indicates the username required to access a resource
|HTTP Password|Indicates the password associated with the provided HTTP Login username
|Preemptive|Option to send the authentication credentials before a server gives an unauthorized response. Currently always true, due to https://github.com/apache/hop/issues/4196[bug #4196].
|Proxy Host|Indicates the name of a proxy host
|Proxy Port|Indicates the port number of a proxy host
|===

=== SSL Tab

The SSL tab is where you provide authentication details for accessing a resource that requires SSL certificate authentication.

[options="header"]
|===
|Option|Description
|Truststore file|Indicates the location of a truststore file
|Truststore password|Indicates the password associated with the provided truststore file
|===

=== Headers Tab

The Headers tab enables you to define the content of any HTTP headers using an existing field. Populate the list of fields by clicking the Get fields button.

TIP: To figure out what Headers are required, you can use Postman and remove as many headers as possible for the Request to still work. You should not need to use the Headers with value “<calculated when request is sent>” in Postman. You do not need to manually add an Authorization header if you used the Authentication tab.

[options="header"]
|===
|Option|Description
|Field|The field from incoming Hop stream that contains the header information. Add the header value field name to the Field column.
|Name|The name of the outgoing Hop field from this transform. Add the header key field name to the Name column.
|===

=== Parameters Tab

The Parameters tab enables you to define parameter values for POST, GET, PUT, and DELETE requests.

[options="header"]
|===
|Option|Description
|Parameter|The field from incoming Hop stream that contains the parameter information
|Parameter|The name of the outgoing Hop field from this transform
|===

=== Matrix Parameters tab

Use the Matrix Parameters tab to define matrix parameter values for POST, PUT, DELETE, and PATCH requests.

[options="header"]
|===
|Option|Description
|Parameter|The field from the incoming Hop stream that contains the matrix parameter information
|Parameter|The name of the outgoing Hop field from this transform
|===
