////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US


=== Connection

Enter the connection information in the following transform options:

[option="header",width="90%"]
|===
|Option|Description
|Salesforce Webservice URL a| Specify the URL to the Salesforce Webservice. +

Default: https://login.salesforce.com/services/Soap/u/50.0

|Username|Specify the username for authenticating to Salesforce
|Password|Specify the password for authenticating to Salesforce.
Enter your password followed by your security token.
For example, if your password is PASSWORD and your security token is TOKEN, you would enter PASSWORDTOKEN in this field.
|Test Connection|Click to verify the connection can be made to the Salesforce Webservice URL you specified.
|===