////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US

=== Fields

You can specify what fields to insert into your Salesforce database through the Fields table.
Click Get fields to populate the table with input from the Hop data stream.

The table contains the following columns:

[options="header",width="90%"]
|===
|Option|Description
|Module field|The name of the field within the Module
|Stream field|The name of the field in the Hop data stream
|Use External id? a|The flag indicating if the field links to an external ID.
To resolve the ID, Salesforce needs the object type, column name, and relationship name in the following syntax: +

[source,shell]
Object name.column name/relationship

|===

Optionally, click Edit mapping to specify custom mapping.
For example, you can map a single Hop field to multiple Salesforce fields.
