////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Sample Rows transform retains a sample set of rows.

= Sample Rows

== Description

The Sample Rows transform retains a sample set of rows.

== Options

[width="90%",options="header"]
|===
|Option|Description
|Transform name|the name for this transform
|Lines range|Specify a comma separated list of rows you want to sample.
This list can contain single line numbers or line number ranges, e.g `10,20,30,40,50..60` to sample rows 10, 20, 30, and 40, and all lines from 50 to 60.
|Line nr fieldname|fieldname to store the line number
|===
