////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Get Server Status transform contacts the Hop servers for which the names are read from an input field.

= Get Server Status

== Description

The Get Server Status transform contacts the Hop servers for which the names are read from an input field.

It returns high level information about the server.
Every output field for which you specify a name will be added to the list of output fields.

== Options

Here is the list of possible output fields:

* Error message
* Status description
* Server load
* Free memory
* Total memory
* CPU cores
* CPU process time
* OS name
* OS version
* OS architecture
* # Active pipelines
* # Active workflows
* Available
* Response (ns)

== Metadata Injection Support

All fields of this transform support metadata injection.
You can use this transform with ETL Metadata Injection to pass metadata to your pipeline at runtime.