////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Sorted Merge transform merges rows coming from multiple input transforms providing these rows are sorted themselves on the given key fields.

= image:transforms/icons/sortedmerge.svg[Sorted Merge transform Icon, role="image-doc-icon"] Sorted Merge

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Sorted Merge transform merges rows coming from multiple input transforms providing these rows are sorted themselves on the given key fields.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:cross.svg[Not Supported, 24]
!Flink! image:cross.svg[Not Supported, 24]
!Dataflow! image:cross.svg[Not Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform this name has to be unique in a single pipeline.
|Fields table|Specify the field name and sort direction (ascending/descending); click Get Fields to retrieve a list of fields from the input stream(s).
|===
