////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Splunk Input transform runs a Splunk search query and returns the result as a set of Hop fields

= Splunk input

== Description

The Splunk Input transform runs a Splunk search query and returns the result as a set of Hop fields

Check the xref:metadata-types/splunk-connection.adoc[Splunk Connection docs] for more information about creating a Splunk connection.

== Options

[width="90%",options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Splunk Connection|The Splunk connection to use
|Query|The Splunk search query to run
|Returns a|The list of fields returned by the Splunk query:

* Field name: the field name to store as an output field for this transform
* Splunk name: the field name (key) returned by the Splunk search
* Return type: search result field data type
* Length: length of the result field
* Format: format for the result field
|===
