////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Cassandra SSTable Output transform writes to a file system directory as a Cassandra SSTable.

= image:transforms/icons/cassandra.svg[Cassandra SSTable Output transform Icon, role="image-doc-icon"] Cassandra SSTable Output

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description

The Cassandra SSTable Output transform writes to a file system directory as a Cassandra SSTable.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

[options="header"]
|===
|Option|Description
|Transform name|the name to use for this transform
|Cassandra yaml file|The cassandra.yaml configuration file to use
|Directory|the directory to output to
|Keyspace|the keyspace (database) to use
|Table|the table to write to
|Incoming fields to use as the key|The field in the incoming data to use as the key for inserts
|Buffer (MB)|Size (MB) of write buffer
|===
