////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Stanford NLP Transform allows you to parse text and provides the foundational building blocks for higher level text understanding

= image:transforms/icons/stanfordnlp.svg[Stanford NLP transform Icon, role="image-doc-icon"] Stanford NLP Transform

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
|
== Description
Stanford CoreNLP provides a set of natural language analysis tools which can take raw English language text input and give the base forms of words, their parts of speech, whether they are names of companies, people, etc., normalize dates, times, and numeric quantities, mark up the structure of sentences in terms of phrases and word dependencies, and indicate which noun phrases refer to the same entities. It provides the foundational building blocks for higher level text understanding applications.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Single Threaded! image:check_mark.svg[Supported, 24]
!Native Spark! image:check_mark.svg[Supported, 24]
!Beam Spark! image:question_mark.svg[Maybe Supported, 24]
!Beam Flink! image:question_mark.svg[Maybe Supported, 24]
!Beam Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Installation

This transform is not part of the default Hop client.
Install it from the Marketplace perspective in Hop Gui (Stanford NLP, category Transforms), or with the xref:hop-tools/hop-marketplace.adoc[marketplace command line]:

[source,bash]
----
./hop marketplace install hop-transform-stanfordnlp
----

The plugin ships the supporting libraries, but Stanford CoreNLP itself is licensed under the GPL v3 and can not be distributed by the Apache Software Foundation.
Download the following two jars and drop them in the `plugins/transforms/stanfordnlp/lib` folder: +
 +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10.jar[stanford-corenlp 4.5.10] +
- https://repo1.maven.org/maven2/xom/xom/1.3.9/xom-1.3.9.jar[xom 1.3.9]

NOTE: The language models are not distributed either: pick the model for your language and drop it in the same `plugins/transforms/stanfordnlp/lib` folder. +
 +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-arabic.jar[Arabic Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-chinese.jar[Chinese Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-english.jar[English Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-french.jar[French Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-german.jar[German Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-hungarian.jar[Hungarian Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-italian.jar[Italian Model] +
- https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.5.10/stanford-corenlp-4.5.10-models-spanish.jar[Spanish Model]
