////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:description: The Stream Schema Merge transform merges multiple inputs with different structures and creates a combination of fields.

= image:transforms/icons/streamschemamerge.svg[Stream Schema Merge transform Icon, role="image-doc-icon"] Stream Schema Merge

[%noheader,cols="3a,1a", role="table-no-borders" ]
|===
a|
== Description

The Stream Schema Merge transform merges multiple inputs with different structures and creates a combination of fields.

TIP: If the streams to merge contain fields with the same name but different types, these fields with be combined into a single field of type `String`. +
If you want to make sure fields keep their original data type, make sure to convert them to identical types. e.g. through the `Metadata` tab in the xref:/pipeline/transforms/selectvalues.adoc[Select Values] transform.

|
== Supported Engines
[%noheader,cols="2,1a",frame=none, role="table-supported-engines"]
!===
!Hop Engine! image:check_mark.svg[Supported, 24]
!Spark! image:question_mark.svg[Maybe Supported, 24]
!Flink! image:question_mark.svg[Maybe Supported, 24]
!Dataflow! image:question_mark.svg[Maybe Supported, 24]
!===
|===

== Options

[options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Transform|The list of transforms to merge. Fields with identical field names in two or more of the input streams will be combined into a unified field (data type is kept if identical, converted to `String` if different). All fields from all of the input streams will be added to the output stream.
|===

