////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/xml/src/main/doc/xslt.adoc
= XSL Transformation

== Description

The XSL Transformation transform performs XSL Transformations on XML. XSLT is short for link:http://en.wikipedia.org/wiki/XSLT[Extensible Stylesheet Language Transformations].

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|XML fieldname|The name of the field that will contain the XML
|Result fields : fieldname|The name of the output fieldname that will contain the XML after the transformations
|XSL file

* XSL filename defined in a field? : Use this option if your XSLT is defined in a field. 
    If enabled, you can specify the filename field below.
* XSL filename : you can specify the XSLT filename here.
* XSLT Factory : specify the factory to use for the transformations: JAXP or SAXON
|===