////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/zipfile/src/main/doc/zipfile.adoc
= Zip file

== Description

The Zip file transform creates a standard ZIP archive using the options you specify in the dialog. 

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Create target parent folder|Check this option to create the target parent folder
|Overwrite target file|Check this option to overwrite the target file if it exists
|Add zip filename to result|Check this option to add the zip filename to the internal result set
|Source filename field|Define the field that contains the source
|Target filename field|Define the field that contains the target zip filename
|Keep source folders|Check this option to keep the source folder within the target zip filename
|Base folder fieldname|Define the field that contains the base folder that is removed from the filename within the zip (used by the option keep source folders)
|After zip|The action to take after zipping
|Move to folder field|Define the field that contains the target directory to move the source files to after zipping 
|===
