////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:
:description: This is used to register multiple Azure blob storage accounts

= Azure Authentication

== Description
This metadata type can be used to add a new Azure Storage file system to your project. This allows you to connect to multiple storage accounts at the same time.
Using an Azure authentication to connect to a blob store requires you to specify the container name in the path. For example, if your Azure authentication is named az, you would need to specify the container as **az:/containerName**.

== Options

[options="header"]
|===
|Option |Description
|Name| Name of the file system, this will be used in file paths `name://`
|Description| Description field for additional information
|Storage Account Name| Name of the storage account in Azure
|Storage Account Key| The primary or secondary key of the storage account
|Storage Endpoint| Leave empty for default Azure endpoints or fill in when using a compatible service
|===
