////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

:documentationPath: /metadata-types/
:language: en_US

= Elastic Location Type

== Description

With this location type you can store execution information in an Elastic database.

== Options

* *Elastic base server URL*: The base URL of the Elastic server, including its port. For example: `http://localhost:9200`
* *The Elastic API Key to use*: The API key of the Elastic server
* *The index name to use*: The name of the index to store the execution information in.
* *Button 'Create and configure Elastic index'*: This executes a number of commands to create and configure the specified index in such a way that Hop can store and retrieve information from Elastic.

