////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:page-pagination:

= Hop Server

== Description

image:icons/server.svg[]

Hop Server is a lightweight web server that hosts a Hop runtime for remote execution, with a web interfaces and a set of servlets to check execution status etc.

Check the xref:hop-server/index.adoc[Hop Server docs] for more details.

== Related Plugins

None/All

== Options

[options="header"]
|===
|Option|Description
|Server name|the name to use for this server definition
|Hostname or IP address|
|Port (empty is port 80)|
|Web app name (optional)|
|Username|
|Password|
|Use https protocal|default: false
|===

== Samples

None