////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:page-pagination:
:description:

= Mail server connection

image:icons/mail.svg[Mail Server Connection, width=24px]

A Mail Server connection is a connection to a mail server that can be reused from actions like the xref:workflow/actions/mail.adoc[Mail] action. Support for other e-mail related actions and transforms will be added in a later release.

== Related Plugins

xref:workflow/actions/mail.adoc[Mail] action

== Options

[options="header"]
|===
|Option |Description
|Connection name|The name to use for this mail server connection
|Connection protocol|The connection protocol to use for this connection. Supported options are SMTP, IMAP, POP, MBOX (Only SMTP is currently supported).
|Server host|The mail server hostname to use for this connection
|Server port|The mail server port to use for this connection
|Use authentication?|Use authentication with this connection?
|User XOAuth2?|Use XOAuth2 authentication for this mail server connection?
|Username|The username to use for this connection
|Password|The password to use for this connection
|Use secure authentication?|Use secure authentication for this connection?
|Secure authentication type|The secure authentication type to use for this connection. Supported options are SSL, TLS, TLS1.2
|Check server identity?|Check the server identity?
|Trusted hosts|A list of trusted hosts separated by a space, for example: "host1 host2 host3"
|Use proxy?|Use a proxy server with this mail server connection?
|Proxy username|The proxy username to use for this connection
|Proxy password|The proxy password to use for this connection
|===

== Samples

None