////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:
:description: Describes a partition schema. A partition schema defines how many ways the row stream will be split. The names used for the partitions can be anything you like.


= Partition Schema

== Description

image:icons/partition_schema.svg[]

Describes a partition schema.
A partition schema defines how many ways the row stream will be split.
The names used for the partitions can be anything you like.

== Related Plugins

None/All

== Options

[options="header"]
|===
|Option|Default|Description
|Partition schema name||The name to be used for this partition schema
|Dynamically create the schema definition|?|
|Number of partitions?|4|
|Partitions||list of partition IDs
|===

== Samples (Integration Tests)

* integration-tests/partitioning/0006-partitioned-when-stream-lookup-should-fail2.hpl
* integration-tests/partitioning/0004-copies-repartitioning.hpl
* integration-tests/partitioning/0001-static-partitioning.hpl
* integration-tests/partitioning/0005-partitioned-stream-lookup.hpl
* integration-tests/partitioning/0006-partitioned-when-stream-lookup-should-fail.hpl
* integration-tests/partitioning/0003-repartitioning.hpl
* integration-tests/partitioning/0005-non-partitioned-stream-lookup.hpl
* integration-tests/partitioning/0002-dynamic-partitioning.hpl