////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:

= Pipeline Run Configuration

== Description

image:icons/pipeline_run_config.svg[]

Describes how and with which engine a pipeline is to be executed.

Pipelines can be executed on a variety of runtime engines.
Check xref:pipeline/pipeline-run-configurations/pipeline-run-configurations.adoc[Pipeline Run Configurations] for more details.

== Related Plugins

None/All

== Options

[options="header"]
|===
|Option|Description
|Name|the name to be used for this pipeline run configuration
|Description|the description to be used for this pipeline run configuration
|Engine Type
a|The available pipeline engines are listed below.
Detailed configuration depends on the xref:pipeline/pipeline-run-configurations/pipeline-run-configurations.adoc[selected engine].

* *xref:pipeline/pipeline-run-configurations/beam-dataflow-pipeline-engine.adoc[Beam DataFlow pipeline engine]*
* *xref:pipeline/pipeline-run-configurations/beam-direct-pipeline-engine.adoc[Beam Direct pipeline engine]*
* *xref:pipeline/pipeline-run-configurations/beam-flink-pipeline-engine.adoc[Beam Flink pipeline engine]*
* *xref:pipeline/pipeline-run-configurations/beam-spark-pipeline-engine.adoc[Beam Spark pipeline engine]*
* *xref:pipeline/pipeline-run-configurations/native-local-pipeline-engine.adoc[Hop local pipeline engine]*
* *xref:pipeline/pipeline-run-configurations/native-remote-pipeline-engine.adoc[Hop remote pipeline engine]*
|===

== Samples

Your Hop installation comes with a default 'local' pipeline run configuration.