////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:
:description: Describes a test for a pipeline. During the test, alternative data sets are used as input from a given transform and testing output against a golden data set. When the result set produced by the pipeline execution matches the expected result (golden data set), the test succeeds. If the generated results do not match what was expected, the test fails.

= Pipeline Unit Test

== Description

image:icons/Test_tube_icon.svg[]

Describes a test for a pipeline. During the test, alternative data sets are used as input from a given transform and testing output against a golden data set.

When the result set produced by the pipeline execution matches the expected result (golden data set), the test succeeds. If the generated results do not match what was expected, the test fails.

Specific transforms in a pipeline can be bypassed or removed for testing for addtional flexibility.

Additionally, unit tests can be executed in bulk.

Check xref:/pipeline/pipeline-unit-testing.adoc[Pipeline Unit Testing^] for more details.

== Related Plugins

None/All

== Options

[options="header"]
|===
|Option|Default|Description
|Name||the name to use for this unit test
|Description||the description to use for this unit test
|Type of test|Development|'Development' or 'unit test'
|The pipeline to test||the pipeline that will be tested by this unit test
|Test pipeline filename (Optional)||
|Base test path (or use HOP_UNIT_TESTS_FOLDER)||
|Select this test automatically|false|
|Replace a database connection with another||List of database connections in the pipeline to test (Original DB) to replace by database connections in this unit test (Replacement DB)
|Variables||list of variable names and values to use for this test
|===

== Samples

 None
