////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:

= Web Service

== Description

image:icons/server.svg[]

Hop has a simple way of exposing data through a servlet.

== Related Plugins

None/All

== Options

[options="header"]
|===
|Option |Description
|Name|The name of the web service.  This is the name that is passed into the webService URL.
|Enabled|Enables or disabled the web service
|Filename on the server|This is the filename on the server.  Make sure that the pipeline you want to execute is available on the server.
|Output transform|The name of the transform from which this service will take the output row(s).
|Output field|The output field from which this service will take data from, convert it to a String and output it
|Content type|The content type which will get reported by the webService servlet
|List status on server|Enable this option if you want the executions of the web service pipeline to be listed in the status of the server.
|===

== Samples

None