////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:imagesdir: ../../assets/images/
:page-pagination:
:page-pagination-no-next:

= Workflow Run Config

== Description

image:icons/workflow_run_config.svg[]

Describes how to run a workflow

Workflows can be executed either locally or remotely. Check xref:workflow/workflow-run-configurations/workflow-run-configurations.adoc[Workflow Run Configurations] for more details.


== Related Plugins

None/All actions

== Options

[options="header"]
|===
|Option|Description
|Name|the name to use for this workflow run configuration
|Description|the description to use for this workflow run configuration
|Workflow engine type|Hop local workflow engine or Hop remote workflow engine
|Safe mode|(default: false) In safe mode, Hop performs a number of data type and other validation before starting the workflow execution.
|===

== Samples

Your Hop installation comes with a default 'local' workflow run configuration.

