/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.core.svg;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import java.awt.Font;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

class HopSvgGraphics2DTest {

  private static final String BASIC_SVG_XML =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?><svg fill-opacity=\"1\" color-rendering=\"auto\" color-interpolation=\"auto\" text-rendering=\"auto\" "
          + "stroke=\"black\" stroke-linecap=\"square\" stroke-miterlimit=\"10\" shape-rendering=\"auto\" stroke-opacity=\"1\" fill=\"black\" stroke-dasharray=\"none\" font-weight=\"normal\" "
          + "stroke-width=\"1\" font-family=\"'Verdana', 'DejaVu Sans', 'Lucida Sans', 'Lucida Grande', 'Arial', 'Helvetica', sans-serif\" font-style=\"normal\" stroke-linejoin=\"miter\" font-size=\"12px\" stroke-dashoffset=\"0\" image-rendering=\"auto\" xmlns=\"http://www.w3"
          + ".org/2000/svg\">\n"
          + "  <!--Generated by the Batik Graphics2D SVG Generator-->\n"
          + "  <defs id=\"genericDefs\"/>\n"
          + "  <g/>\n"
          + "</svg>\n";

  private static final String BASIC_CIRCLE_XML =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?><svg fill-opacity=\"1\" color-rendering=\"auto\" color-interpolation=\"auto\" text-rendering=\"auto\" "
          + "stroke=\"black\" stroke-linecap=\"square\" stroke-miterlimit=\"10\" shape-rendering=\"auto\" stroke-opacity=\"1\" fill=\"black\" stroke-dasharray=\"none\" font-weight=\"normal\" "
          + "stroke-width=\"1\" font-family=\"'Verdana', 'DejaVu Sans', 'Lucida Sans', 'Lucida Grande', 'Arial', 'Helvetica', sans-serif\" font-style=\"normal\" stroke-linejoin=\"miter\" font-size=\"12px\" stroke-dashoffset=\"0\" image-rendering=\"auto\" xmlns=\"http://www.w3"
          + ".org/2000/svg\">\n"
          + "  <!--Generated by the Batik Graphics2D SVG Generator-->\n"
          + "  <defs id=\"genericDefs\"/>\n"
          + "  <g>\n"
          + "    <g>\n"
          + "      <circle fill=\"none\" r=\"12.5\" cx=\"62.5\" cy=\"62.5\"/>\n"
          + "    </g>\n"
          + "  </g>\n"
          + "</svg>\n";

  @Test
  void testNewDocumentXml() throws Exception {
    HopSvgGraphics2D graphics2D = HopSvgGraphics2D.newDocument();
    XmlMapper xmlMapper = new XmlMapper();
    JsonNode graphic2DNode = xmlMapper.readTree(graphics2D.toXml());
    JsonNode basicSVGNode = xmlMapper.readTree(BASIC_SVG_XML);
    assertEquals(basicSVGNode, graphic2DNode);
  }

  @Test
  void testNewDocumentSimpleXml() throws Exception {
    HopSvgGraphics2D graphics2D = HopSvgGraphics2D.newDocument();

    graphics2D.drawOval(50, 50, 25, 25);

    XmlMapper xmlMapper = new XmlMapper();
    JsonNode graphic2DNode = xmlMapper.readTree(graphics2D.toXml());
    JsonNode basicSVGNode = xmlMapper.readTree(BASIC_CIRCLE_XML);
    assertEquals(basicSVGNode, graphic2DNode);
  }

  /** A browser has no 'Dialog' font: the logical AWT families become a web font stack. */
  @Test
  void testLogicalFontFamiliesBecomeWebFontStacks() {
    assertTrue(HopSvgGraphics2D.toWebFontFamily("'Dialog'").endsWith("sans-serif"));
    assertTrue(HopSvgGraphics2D.toWebFontFamily("sans-serif").endsWith("sans-serif"));
    assertTrue(HopSvgGraphics2D.toWebFontFamily("'Monospaced'").endsWith("monospace"));
    assertTrue(HopSvgGraphics2D.toWebFontFamily("'Serif'").endsWith("serif"));
    assertFalse(HopSvgGraphics2D.toWebFontFamily("'Dialog'").contains("Dialog"));

    // A concrete family keeps the lead and gets the sans-serif stack as fallback, once.
    String segoe = HopSvgGraphics2D.toWebFontFamily("'Segoe UI'");
    assertTrue(segoe.startsWith("'Segoe UI', "));
    assertTrue(segoe.endsWith("sans-serif"));
    String verdana = HopSvgGraphics2D.toWebFontFamily("'Verdana'");
    assertEquals(1, verdana.split("'Verdana'", -1).length - 1);
  }

  /** The text run is pinned to the width the JVM measured, so the browser lays it out the same. */
  @Test
  void testDrawStringPinsTextLength() throws Exception {
    HopSvgGraphics2D graphics2D = HopSvgGraphics2D.newDocument();
    Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 10);
    graphics2D.setFont(font);
    graphics2D.drawString("Table input", 20, 40);
    String xml = graphics2D.toXml();

    Matcher matcher =
        Pattern.compile("<text[^>]*textLength=\"([0-9.]+)\"[^>]*>Table input</text>").matcher(xml);
    assertTrue(matcher.find(), xml);
    double expected =
        font.getStringBounds("Table input", graphics2D.getFontRenderContext()).getWidth();
    assertEquals(expected, Double.parseDouble(matcher.group(1)), 0.001);
    assertTrue(xml.contains("x=\"20\""), xml);
    assertTrue(xml.contains("y=\"40\""), xml);
    assertFalse(xml.contains("'Dialog'"), xml);
    assertFalse(xml.contains("'SansSerif'"), xml);
  }

  /**
   * A string no font on this JVM has glyphs for (CJK on a JVM without a CJK font, #8528) is not
   * pinned: the only width known for it is that of missing-glyph boxes, so the browser must lay it
   * out itself. U+0378 is unassigned, so no font on any platform has a glyph for it.
   */
  @Test
  void testDrawStringDoesNotPinUndisplayableText() throws Exception {
    HopSvgGraphics2D graphics2D = HopSvgGraphics2D.newDocument();
    Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 10);
    graphics2D.setFont(font);
    String text = "Table\u0378input";
    assertTrue(font.canDisplayUpTo(text) >= 0, "test needs an undisplayable character");
    assertNull(HopSvgGraphics2D.measuringFont(font, text));
    graphics2D.drawString(text, 20, 40);
    String xml = graphics2D.toXml();

    assertTrue(xml.contains("<text"), xml);
    assertFalse(xml.contains("textLength"), xml);
    assertTrue(xml.contains("x=\"20\""), xml);
    assertTrue(xml.contains("y=\"40\""), xml);
  }

  /**
   * Text the canvas font lacks glyphs for is measured with the logical SansSerif font, which falls
   * back through the platform font configuration, when that font can display it. A physical font
   * that has the glyphs is kept as is.
   */
  @Test
  void testMeasuringFontFallsBackToLogicalFont() {
    Font physical = new Font(Font.SANS_SERIF, Font.BOLD, 10).deriveFont(10.5f);
    assertSame(physical, HopSvgGraphics2D.measuringFont(physical, "Table input"));
    assertSame(physical, HopSvgGraphics2D.measuringFont(physical, ""));
    assertNull(HopSvgGraphics2D.measuringFont(null, "Table input"));

    // Whether the JVM has a CJK font depends on the platform; whichever the answer, the outcome is
    // either a logical font of the same style and size or no font at all, never the boxes.
    String cjk = "\u8868\u8f93\u5165";
    Font measuring = HopSvgGraphics2D.measuringFont(new Font("DejaVu Sans", Font.BOLD, 10), cjk);
    if (measuring != null) {
      assertEquals(-1, measuring.canDisplayUpTo(cjk));
      assertEquals(Font.BOLD, measuring.getStyle());
      assertEquals(10, measuring.getSize());
    }
  }
}
