////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/delay/src/main/doc/delay.adoc
= Delay row

== Description

For each input row, the "Delay row" transform will wait the indicated timeout period before giving the row to the next transform.

Use this transform if you deliberately want to slow down your pipeline.

== Options

[width="90%", options="header"]
|===
|Option|Description
|transform name|Name of the transform. Note: This name has to be unique in a single pipeline.
|Timeout|The timeout value in seconds, minutes or hours 
|===