////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/as400command/src/main/doc/as400command.adoc
= AS/400 Command

== Description

This action is for executing a AS/400 CL Commands.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Action name|The name of the workflow action.
|Server|Host name or IP address.
|User name|The user name associated with AS/400 server account.
|Password|The password associated the AS/400 server account.
|Proxy host|Proxy server host name or IP address.
|Proxy port|Proxy server port number.
|Command to call|The command to run on the AS/400. If the command is not library qualified, the library list will be used to find the command.
|===

NOTE: This plugin tries to load the as400 library from the as400 database plugin.