#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Generate JFrog Artifactory security keys for docker-compose:
#   - master.key  AES-128 → openssl rand -hex 16  (32 hex chars)
#   - join.key    cluster join → openssl rand -hex 32 (64 hex chars)
#
# Keys are written under keys/ and also mirrored into .env for compose
# (JF_SHARED_SECURITY_MASTER_KEY / JF_SHARED_SECURITY_JOIN_KEY).
#
# Usage:
#   ./docker/marketplace-artifactory/generate-keys.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="${SCRIPT_DIR}/keys"
ENV_FILE="${SCRIPT_DIR}/.env"

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required on the host" >&2
  exit 1
fi

mkdir -p "${KEYS_DIR}"

# $1=filename $2=openssl hex byte count (16 → 32 chars, 32 → 64 chars)
ensure_key() {
  local name="$1"
  local bytes="$2"
  local expected_len=$((bytes * 2))
  local dest="${KEYS_DIR}/${name}"

  if [[ -f "${dest}" ]]; then
    local len
    len="$(wc -c < "${dest}" | tr -d ' ')"
    if [[ "${len}" == "${expected_len}" ]]; then
      echo "Key already exists: ${dest} (${len} bytes)"
      return 0
    fi
    echo "Replacing invalid ${dest} (length ${len}, expected ${expected_len})"
  else
    echo "Generating ${name} (openssl rand -hex ${bytes})..."
  fi

  # No trailing newline
  openssl rand -hex "${bytes}" | tr -d '\n' > "${dest}"
  chmod 600 "${dest}" 2>/dev/null || true
  echo "Wrote ${dest}"
}

ensure_key "master.key" 16
ensure_key "join.key" 32

MASTER_KEY="$(cat "${KEYS_DIR}/master.key")"
JOIN_KEY="$(cat "${KEYS_DIR}/join.key")"

# Compose reads these as JF_SHARED_SECURITY_* (no file mounts — Artifactory
# tries to rewrite key files and RO bind-mounts fail).
cat > "${ENV_FILE}" <<EOF
# Generated by generate-keys.sh — do not commit
JF_SHARED_SECURITY_MASTER_KEY=${MASTER_KEY}
JF_SHARED_SECURITY_JOIN_KEY=${JOIN_KEY}
POSTGRES_PASSWORD=hop_artifactory_dev
EOF
chmod 600 "${ENV_FILE}"

echo "Wrote ${ENV_FILE} for docker compose"
echo "Done. Start with:"
echo "  ./docker/marketplace-artifactory/start.sh"
echo "  # or: docker compose -f docker/marketplace-artifactory/docker-compose.yml --env-file docker/marketplace-artifactory/.env up -d"
