////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/pgp/src/main/doc/pgpdecryptstream.adoc
= PGP decrypt stream

== Description

The PGP decrypt stream transform decrypts PGP encrypted text.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|GPG location|GPG key location.
|Browse...|Browse the filesystem for a GPG key location.
|Passphrase|Passphrase of the key.
|Read passphrase from field|Whether or not to read the passphrase from a field.
|Passphrase fieldname|The passphrase field.
|Data fieldname|The field to decrypt.
|Result fieldname|The decrypted result field.
|===
