////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/mapping/src/main/doc/mapping-input.adoc
= Mapping Input

== Description

This transform is not just a place-holder in a Mapping pipeline (referred to as a Mapping), it represents and describes its input.  The data of this input will be provided for by the parent pipeline calling the mapping.

== Options

The fields described in this transform are those that you want to refer to in this pipeline.  When you use the mapping you can map input to these field names to arrive at a re-usable part of a pipeline.
