////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/workflow/actions/mysqlbulkfile/src/main/doc/mysqlbulkfile.adoc
= MySQL Bulk File

== Description

The MySQL Bulk File action can bulk load data from MySQL into a file.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Connection|The database connection.
|Edit...|Edit the database connection.
|New...|Create a new database connection using the standard dialog.
|Wizard...|Create a new database connection using the wizard dialog.
|Target schema|The target schema.
|Target File name|The target file.
|High Priority|The priority to load the file with.
|Type|OUTFILE, DUMPFILE
|Field separator|The field separator to use.
|Fields enclosed by|The field enclosure to use.
|Optionally enclosed|
|Lines terminated by|The line termination string to use.
|Names of columns|
|Limit to the...first lines|
|If file exists|Create new with unique name, Do Nothing, Fail
|Add file to result filenames|
|===
