////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/insertupdate/src/main/doc/insertupdate.adoc
= Insert / Update

== Description

The Insert/Update transform first looks up a row in a table using one or more lookup keys. If the row can't be found, it inserts the row. If it can be found and the fields to update are the same, nothing is done. If they are not all the same, the row in the table is updated.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Commit size|The number of rows to change (insert / update) before running a commit.
|Connection|The database connection to which data is written
|Don't perform any updates|If enabled, the values in the database are never updated;only inserts are performed.
|Key Lookup table|Allows you to specify a list of field values and comparators. You can use the following comparators: =, = ~NULL, <>, <, <=, >, >=, LIKE, BETWEEN, IS NULL, IS NOT NULL
|SQL button|Click SQL to generate the SQL to create the table and indexes for correct operation.
|Transform name|Name of the transform; this name has to be unique in a single pipeline.
|Target schema|The name of the Schema for the table to which data is written. This is important for data sources that allow for table names with periods in them.
|Target table|Name of the table in which you want to do the insert or update.
|Update Fields|Allows you to specify all fields in the table you want to insert/update including the keys. Avoid updates on certain fields by specifying N in the update column.
|===