////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Building and setting up your own Hop Web environment is straightforward. The steps to set up the default Docker image are included in a helper script docker/create_hop_web_container.sh in the Hop code base. This should get you started to make modifications or create your own version entirely.

= Hop Web Development Guide

== Building or customizing Hop Web

Building and setting up your own Hop Web environment is straightforward.

The steps to set up the default Docker image are included in a helper script `docker/create_hop_web_container.sh` in the Hop code base.
This should get you started to make modifications or create your own version entirely.

[source,bash]
----
#set working dir to current location
cd "${0%/*}"

#unzip files for docker image
unzip ../assemblies/web/target/hop.war -d ../assemblies/web/target/webapp
unzip ../assemblies/plugins/dist/target/hop-assemblies-*.zip -d ../assemblies/plugins/dist/target/

#build docker image
docker build ../ -f Dockerfile.web -t hop-web

#cleanup
rm -rf ../assemblies/web/target/webapp
rm -rf ../assemblies/plugins/dist/target/plugins
----

== Additional Guides

* xref:hopweb/developer-guide.adoc[Developer Guide]
* xref:hopweb/hopweb-antipatterns.adoc[Hop Web Antipatterns]
