////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/tableexists/src/main/doc/tableexists.adoc
= Table Exists

== Description

You can use the Table Exists transform to verify if a certain table exists in a database.  The result of this transform is a boolean flag field.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|The name of the transform. This name has to be unique in a single pipeline.
|Connection|The database connection to use
|Schema name|The schema of the table to look for
|Table name field|The name of the field that will contain the database table name to look for.
|Result fieldname|The name of the field that will contain the boolean result flag in the output of this transform.
|===
