////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/getsubfolders/src/main/doc/getsubfolders.adoc

= Get SubFolder names

== Description

The Get Subfolder Names transform gets subfolders from a directory.

== Options

=== Folder tab

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of this transform as it appears in the pipeline workspace
|Accept foldername from field?|Allows a foldername to be passed as a field.
|Foldername field|The field which contains the folder name.
|Selected directories|The directories from which to get the subfolders.
|Browse|Uses the local file browser to get a path.
|Add|Adds the path defined in the Directory field.
|Delete|Deletes the path
|Edit|Change the path
|===


=== Settings tab

[width="90%", options="header"]
|===
|Option|Description
|Include rownum in output?|Allows the row number to be added to the output.
|Rownum fieldname|The field which contains the row number.
|Limit|Limits the output rows.
|===