/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.pipeline.transforms.dimensionlookup;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Set;
import org.apache.hop.lineage.LineageMetadataWalker;
import org.apache.hop.lineage.LineageMetadataWalker.ColumnMapping;
import org.apache.hop.lineage.LineageMetadataWalker.Declaration;
import org.apache.hop.lineage.model.RelationalIoOperation;
import org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta.DLField;
import org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta.DLFields;
import org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta.DLKey;
import org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta.DLReturn;
import org.junit.jupiter.api.Test;

/**
 * Checks the relational lineage Dimension Lookup/Update declares on its metadata.
 *
 * <p>The generated technical key is the interesting case: it is a real dimension column but has no
 * stream field behind it, so it must stay out of the column lineage rather than appear with no
 * origin.
 */
class DimensionLookupLineageTest {

  private static DimensionLookupMeta meta() {
    DimensionLookupMeta meta = new DimensionLookupMeta();
    meta.setConnection("warehouse");
    meta.setSchemaName("staging");
    meta.setTableName("dim_orders");

    DLKey key = new DLKey();
    key.setName("id");
    key.setLookup("order_id");

    DLField field = new DLField();
    field.setName("amount");
    field.setLookup("total");

    // The technical key is generated by the transform: a column with no stream field behind it.
    DLReturn returns = new DLReturn();
    returns.setKeyField("dim_tk");

    DLFields fields = new DLFields();
    fields.setKeys(List.of(key));
    fields.setFields(List.of(field));
    fields.setReturns(returns);
    meta.setFields(fields);
    return meta;
  }

  @Test
  void declaresAWriteToTheDimensionTable() {
    Declaration declaration = LineageMetadataWalker.read(meta());

    assertNotNull(declaration, "Dimension Lookup should declare relational lineage");
    assertEquals(RelationalIoOperation.WRITE, declaration.operation());
    assertEquals("warehouse", declaration.connectionName());
    assertEquals("staging", declaration.schemaName());
    assertEquals("dim_orders", declaration.tableName());
    assertTrue(declaration.isUsable());
  }

  @Test
  void mapsStreamFieldsToDimensionColumnsAndLeavesTheTechnicalKeyOut() {
    Declaration declaration = LineageMetadataWalker.read(meta());

    assertEquals(
        Set.of(new ColumnMapping("order_id", "id"), new ColumnMapping("total", "amount")),
        Set.copyOf(declaration.columns()));
    assertFalse(
        declaration.columns().stream().anyMatch(c -> "dim_tk".equals(c.targetColumn())),
        "the generated technical key has no stream field and must not appear in column lineage");
  }
}
