////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/injector/src/main/doc/injector.adoc
= Injector

== Description

Injector was created for those people that are developing special purpose pipelines and want to 'inject' rows into the pipeline using the Hop API and Java. Among other things you can build 'headless' pipelines with it: pipelines that have no input at design time: do not read from file or database.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Fieldname|Specify the field name of the rows to inject.
|Type|Specify the type of data.
|Length|For Number: Total number of significant figures in a number; For String: total length of string; For Date: length of printed output of the string.
|Precision|For Number: Number of floating point digits; For String, Date, Boolean: unused. 
|===