////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/workflow/actions/dostounix/src/main/doc/dostounix.adoc
= Dos To Unix

== Description

Convert files from Windows (DOS) Format (lines end with CR/LF) to Linux/Unix Format (lines end with LF) and vice versa. When the format is unknown, it has also a guess function and converts to the other format.

== Options

=== General

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Settings a|
* Include Subfolders: also process sub-folders
* Copy previous results to args : use the list of result files from the previous workflow action (actions) in stead of the static file list below.
|Files / Folders a| 
You can specify the list of files or folders with wildcards in this grid.
You can add a different source/destination on each line.
|Conversion a|
This can be:

* Windows to Unix: Convert files from Windows (DOS) Format (lines end with CR/LF) to Linux/Unix Format (lines end with LF)
* Unix to Windows: Convert files from Linux/Unix Format (lines end with LF) to Windows (DOS) Format (lines end with CR/LF)
* Guess: When the format is unknown, it converts to the other format.
|===

=== Advanced

[width="90%", options="header"]
|===
|Option|Description
|Success Condition|This action will follow the success path if the selected condition is true. Current options are: "Success if all files are processed", "Success if at least x files are processed", "Success when number of error files lesser than".
|Nr Files|specifies the number of files that have to meet the selected condition from above
|Add Filenames|Adds the filenames that meet the selected condition to the workflow output stream. Conditions are: "Do not add filenames", "Add all filenames", "Add only processed filenames" or "Add only error filenames" 
|===