////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/folderisempty/src/main/doc/folderisempty.adoc
= Folder is Empty

== Description

The Folder is empty action verifies if a folder is empty, that there are no regular files or sub-folders in the folder.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action. This name has to be unique in a single workflow.
|Folder name|The name of the folder to verify for emptiness.
|Limit search to|Limits the search for files to those with a certain wildcard (regular expression)
|Wildcard|The wildcard (regular expression) to limit the files to look for with, for example: .*\.txt$ 
|===

