////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /metadata-types/graphs/
:language: en_US
:page-marketplace: hop-tech-neo4j
:page-aliases: metadata-types/neo4j/neo4j-graphmodel.adoc

= Graph Model

== Description

A graph model describes (part of) a graph by allowing you to define nodes with their properties, and the relationships that connect these nodes.
You can then use such a Graph Model to map input fields to properties in the xref:pipeline/transforms/graph-output.adoc[Graph output] transform, for any graph database.

Every property has a type.
Use `Vector` for embeddings, for example the output of the xref:pipeline/transforms/embedtext.adoc[Embed text] transform, see xref:technology/graph-databases/index.adoc#vectors[Vectors and embeddings].

