////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

:documentationPath: /metadata-types/neo4j/
:language: en_US

= Neo4j Location Type

== Description

With this location type you can store execution information in a xref:technology/neo4j/index.adoc[Neo4j] graph database.

== Options

* *Neo4j connection*: the name of the xref:metadata-types/neo4j/neo4j-connection.adoc[Neo4j connection] to store the information in.
* *Button 'Show indexes DDL'*: This displays the CREATE INDEX statements that you want to execute on the Neo4j connection to make sure performance is and remains good when writing and reading information.
* *Button 'Copy a Neo4j Index action to clipboard'*: This copies the Neo4j Index action to the clipboard so that you can just copy this in a workflow.  It will make sure that the right indexes are created (if needed) to have great performance when using the execution information location.

== Graph model

This is the graph model that gets populated by this execution information location plugin:

image:metadata-types/neo4j/apache-hop-execution-information-model.svg[The Apache Hop execution information graph model, width="100%"]

