////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/actions/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/actions/setvariables/src/main/doc/setvariables.adoc
= Set Variables

== Description

The Set Variables action can be used to set variables at various scopes.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Workflow action name|The name of the workflow action.
|Name of properties file|The name of the properties file.
|Variable scope a|
* Valid in the Java Virtual machine
* Valid in the current workflow
* Valid in the parent workflow
* Valid in the root workflow
|Variable substitution|Whether or not to substitute variables.
|Variables|A list of variables to set to a certain value at a certain scope.
|===
