[[Technology]]
////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:description: Hop integrates with tens if not hundreds of different technologies. The Azure, Apache Cassandra, Google and Neo4j platforms are supported at various points in Hop and are covered in their own section.

= Technology

This section contains technology-stack specific information.
The goal is to inform you about how Apache Hop offers support for the technology in question.
It also provides starting points for you if you want to learn more about the technology.

The technologies supported by Hop currently include:

* xref:technology/azure/index.adoc[Azure]
* xref:technology/cassandra/index.adoc[Apache Cassandra]
* xref:technology/google/index.adoc[Google]
* xref:technology/neo4j/index.adoc[Neo4j]
** xref:technology/neo4j/working-with-neo4j-data.adoc[Working with Neo4j data]
