////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/streamschemamerge/src/main/doc/streamschemamerge.adoc
= Stream Schema Merge

== Description

This transform type allows you to merge multiple inputs with different structures. It will then create a combination of fields.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Transform|The transforms to merge.
|OK|Confirms the current settings
|Get|Populates the Transform column with all transforms connected to this transform
|Cancel|Cancels the current settings
|===

