////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/blockuntiltransformsfinish/src/main/doc/blockuntiltransformsfinish.adoc
= Blocking until transforms finish

== Description

This transform simply waits until all the transform copies that are specified in the dialog have finished. 

You can use it to avoid the natural concurrency (parallelism) that exists between pipeline transform copies.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform.
|Watch the following transforms|Use this grid to specify the transforms to wait for.
|Get transforms|Push this button to auto-fill the "Watch the following transforms" grid with all transforms available in the pipeline.
|===

[width="90%", options="header"]
|===
|Option|Description
|transform name|The name of the transform to wait for.
|CopyNr|The (0-based) copy number of the transform. If the named transform has an explicit setting for "Change number of copies to start", and you want to wait for all copies to finish, you'll need to enter one row in the grid for each copy, and use this column to specify which copy of the transform to wait for. For the default number of copies (1), the CopyNr is always 0.
|===