////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/pipeline/transforms/fileexists/src/main/doc/fileexists.adoc
= File exists

== Description

This transforms verifies the existence of a file where the filename comes from previous transforms.

The result is a boolean flag field that gets added to the input fields in the output.

== Options

[width="90%", options="header"]
|===
|Option|Description
|Transform name|Name of the transform; This name has to be unique in a single pipeline
|Filename field|The input field that will contain the filename at runtime
|Result fieldname|The name of the field that will contain the boolean flag.
|Add filename to result|Enable this option if you want to add the filename to the list of filenames that can be used in the next workflow action.
|Include file type|Include the file type in a field.
|File type field|The name of the field that will contain the file type as a String: "file", "folder", "imaginary"
|===
