////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/transforms/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/transforms/filesfromresult/src/main/doc/filesfromresult.adoc
= Files from result

== Description

Every time a file gets processed, used or created in a pipeline or a workflow, the details of the file, the workflow action, the transform, etc. is captured and added to an internal result set when the option 'Add file names to result' is set, e.g. in a Text File Output transform. You can access this file information using this transform.

== Options

[width="90%", options="header"]
|===
|Option|Description
|transform name|The unique transform name within the pipeline 
|===


== Output fields

[width="90%", options="header"]
|===
|Field name|Type|Example
|type|String|Normal, Log, Error, Error-line, etc.
|filename|String|somefile.txt
|path|String|C:\Foo\Bar\somefile.txt
|parentorigin|String|Process files pipeline
|origin|String|Text File Input
|comment|String|Read by text file input
|timestamp|Date|2006-06-23 12:34:56 
|===
